### ISSUE TITLE
FDP

### ISSUE THREAD

**Issue by ARDAPROBABA313131** [UnlegitMC/FDPClient#106]
The new version 1.4.0 has arrived, but fly does not open. Auto disable in blocksmc blocks it and fly in blocksmc should be developed a little more because we are kicked out of the game because of fly, fly bypass should be done better

**Comment by ll11l1lIllIl1lll** [comment]
AutoDisable disabled fly : .autodisable fly none

better fly:
timer speed 0.4
bind timer and fly to same key

**Comment by shuhai2008** [comment]
In our latest 1.4.0, we have made autodisable a separate module, and now it will always be enabled.
The usage of autodisable is:. Autodisable < module > < mode >
You just need to enter ". Autodisable fly none" in the game to solve this problem
I wish you a happy life and all the best
