### ISSUE TITLE
can you tell me why spam issues in this repo

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [UnlegitMC/FDPClient#1106]
I know you will reply no

**Comment by ll11l1lIllIl1lll** [comment]
I understand your misfortune in reality, even if you are an orphan

**Comment by iiiiiieeeegggg** [comment]
for fun

**Comment by ll11l1lIllIl1lll** [comment]
> for fun

ok I need to sleep now

**Comment by ll11l1lIllIl1lll** [comment]
I won't take care of your issues anymore

**Comment by ll11l1lIllIl1lll** [comment]
I believe you don't base your happiness on someone else's pain, do you?

**Comment by ll11l1lIllIl1lll** [comment]
It's already 3:31 in my country

**Comment by iiiiiieeeegggg** [comment]
lol

**Comment by SakurajimaMai02** [comment]
> It's already 3:31 in my country

fdp destroyed their verus

**Comment by TopDogger1** [comment]
> > It's already 3:31 in my country
> 
> fdp destroyed their verus

cringe

**Comment by ll11l1lIllIl1lll** [comment]
I am disappointed.

**Comment by SakurajimaMai02** [comment]
> > > It's already 3:31 in my country
> > 
> > 
> > fdp destroyed their verus
> 
> cringe

cringe

**Comment by ll11l1lIllIl1lll** [comment]
> > > > It's already 3:31 in my country
> > > 
> > > 
> > > fdp destroyed their verus
> > 
> > 
> > cringe
> 
> cringe

cringe

**Comment by liulihaocai** [comment]
> > > > > It's already 3:31 in my country
> > > > 
> > > > 
> > > > fdp destroyed their verus
> > > 
> > > 
> > > cringe
> > 
> > cringe
> 
> cringe

cringe

**Comment by exit-scammed** [comment]
> > > > > > It's already 3:31 in my country
> > > > > 
> > > > > 
> > > > > fdp destroyed their verus
> > > > 
> > > > 
> > > > cringe
> > > 
> > > 
> > > cringe
> > 
> > 
> > cringe
> 
> cringe

cringe

**Comment by Kwenma1** [comment]
> > > > > > > It's already 3:31 in my country
> > > > > > 
> > > > > > 
> > > > > > fdp destroyed their verus
> > > > > 
> > > > > 
> > > > > cringe
> > > > 
> > > > 
> > > > cringe
> > > 
> > > 
> > > cringe
> > 
> > 
> > cringe
> 
> cringe

cringe

**Comment by danik4985** [comment]
@ll11l1lIllIl1lll cringe

**Comment by master7720** [comment]
> cringe

 cringe

**Comment by master7720** [comment]
> > > > > > > > It's already 3:31 in my country
> > > > > > > 
> > > > > > > 
> > > > > > > fdp destroyed their verus
> > > > > > 
> > > > > > 
> > > > > > cringe
> > > > > 
> > > > > 
> > > > > cringe
> > > > 
> > > > 
> > > > cringe
> > > 
> > > 
> > > cringe
> > 
> > 
> > cringe
> 
> cringe

cringe

**Comment by Techlord210** [comment]
> > > > > > > > > > It's already 3:31 in my country
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > fdp destroyed their verus
> > > > > > > > 
> > > > > > > > 
> > > > > > > > cringe
> > > > > > > 
> > > > > > > 
> > > > > > > cringe
> > > > > > 
> > > > > > 
> > > > > > cringe
> > > > > 
> > > > > 
> > > > > cringe
> > > > 
> > > > 
> > > > cringe
> > > 
> > > 
> > > cringe
> > 
> > 
> > cringe
> 
> cringe

cringe
