### ISSUE TITLE
wtf what happened

### ISSUE THREAD

**Issue by SakurajimaMai02** [UnlegitMC/FDPClient#1107]

**Comment by ll11l1lIllIl1lll** [comment]
our repo now has more issues than log4js-node issues

**Comment by ll11l1lIllIl1lll** [comment]
7 times or even 5 times more issues than MCP-reborn

**Comment by SakurajimaMai02** [comment]
> 7 times or even 5 times more issues than MCP-reborn

ik，just shocked
