### ISSUE TITLE
i farted like 2 times

### ISSUE THREAD

**Issue by 14ms** [UnlegitMC/FDPClient#1129]
how to install fdp client

**Comment by SakurajimaMai02** [comment]
step1：install the jar
step2：put it into ur mods file
step3：launch the game

**Comment by 14ms** [comment]
> step1：install the jar step2：put it into ur mods file step3：launch the game

where i can find mods folder on my phone

**Comment by SakurajimaMai02** [comment]
> > step1：install the jar step2：put it into ur mods file step3：launch the game
> 
> where i can find mods folder on my phone

step1：open ur amazon
step2：buy a computer
step3：open it and install Minecraft
step4：find the mods folder

**Comment by ll11l1lIllIl1lll** [comment]
step1：use normal LB
