### ISSUE TITLE
config<Title Here>

### ISSUE THREAD

**Issue by mangoozz** [UnlegitMC/FDPClient#1130]
where to put the config ?

**Comment by ProYT303** [comment]
minecraft directory/fdpclient-1.8/configs/

**Comment by mangoozz** [comment]
do i need to remove anything or just put the config there ?

**Comment by ProYT303** [comment]
put the config there

**Comment by mangoozz** [comment]
ok tyyy <3

**Comment by mangoozz** [comment]
u mean from %appdata% then . minecraft ?

**Comment by SubToApple** [comment]
\AppData\Roaming\.minecraft\FDPClient-1.8\configs (just put this in run)

**Comment by SubToApple** [comment]
> u mean from %appdata% then . minecraft ?

yup

**Comment by mangoozz** [comment]
thanks guys that helped alot <3
