### ISSUE TITLE
Modules State not changing

### ISSUE THREAD

**Issue by mini-programmer** [UnlegitMC/FDPClient#1131]
After some time without playing minecraft i came back, installed latest FDP(Earlyacess) and noticed that for example, when i click on 'BetterFPS' module, its state doesnt change, what i mean is that it says that its enabled but doesnt change anything, there are also other modules that have that same problem, how can i fix it?

**Comment by SakurajimaMai02** [comment]
normal

**Comment by F3D7P6hxg** [comment]
Just install optifine 1.89

**Comment by contionability** [comment]
u don't need to enable that module
it changes the interface of the game as you change the settings in it
