### ISSUE TITLE
FDP Crash

### ISSUE THREAD

**Issue by mini-programmer** [UnlegitMC/FDPClient#1139]
When trying to launch, FDP crashes,
crash report
[crash-2022-02-05_19.37.09-client.txt](https://github.com/UnlegitMC/FDPClient/files/8009047/crash-2022-02-05_19.37.09-client.txt)

**Comment by F3D7P6hxg** [comment]
remove other mod except fdp client and optifine 1.89

**Comment by re-ovo** [comment]
你的CPU型号是什么，似乎无法检测某些cpu型号

**Comment by re-ovo** [comment]
这段代码会导致崩溃 @liulihaocai 
```kotlin
val processorModel = processors.joinToString("-") { it.model }
```
