### ISSUE TITLE
liquidbounce skid

### ISSUE THREAD

**Issue by danik4985** [UnlegitMC/FDPClient#1146]
i can't seem to find any original code in the client. you might want to fix that!

! If you love CCP or you are in china, don't scroll down this page

**Comment by danik4985** [comment]
also why do all the good pull requests get closed?

**Comment by master7720** [comment]
fr ^^^^

**Comment by hi231** [comment]
kys

**Comment by ll11l1lIllIl1lll** [comment]
kys

**Comment by ll11l1lIllIl1lll** [comment]
all client is mcp skid ok

**Comment by master7720** [comment]
......

**Comment by danik4985** [comment]
@hi231 @ll11l1lIllIl1lll imagine using a lb skid

**Comment by danik4985** [comment]
![](https://c.files.bbci.co.uk/B60F/production/_96970664_abexi.jpg)

**Comment by danik4985** [comment]
![](https://i.kym-cdn.com/photos/images/original/001/555/449/7ce.jpg)

**Comment by danik4985** [comment]
btw https://www.youtube.com/watch?v=YeFzeNAHEhU @funcxt @xiguagege @liulihaocai you must watch this

**Comment by danik4985** [comment]
and this https://www.youtube.com/watch?v=WmId2ZP3h0c

**Comment by danik4985** [comment]
also taiwan is an independant country, gona cry?

![](https://www.google.com/maps/vt/data=ozsGvEhGDFoW7z3zEph5GuCQxT5xaU77DjzHG8MQIE0xISDnqqr8vrkQvXCy8dROAzBnyuTgG3URfUuBPt4CehF7q2wPKSU3dExsPHVbKe4KeCg57E1cVFx7v0umY5hFyTVKyvgHC8INS1Iou6YrLHq4TqEHt7qEYg4OvVrorqGm3kVmCytvk5VJd0aKVo4roQWfTm5w1ig5Nfuv_5n8uB6fRYpHtRF-qd4quWLHyzavwfg)

**Comment by danik4985** [comment]
#fucktheccp

**Comment by AmeBeep** [comment]
> i can't seem to find any original code in the client. you might want to fix that!

me neither, also i hate ccp.

**Comment by master7720** [comment]
> @hi231 @ll11l1lIllIl1lll imagine using a lb skid

Fr

**Comment by ll11l1lIllIl1lll** [comment]
[**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1034046311 "2022-02-09T18:04:01Z - Replied by Github Reply Comments"):
> @hi231 @ll11l1lIllIl1lll imagine using a lb skid

shut up nig

**Comment by ll11l1lIllIl1lll** [comment]
go back to your mcp skid client then suck your father's cook

**Comment by ll11l1lIllIl1lll** [comment]
oh i forget you are the fatherless guy XD

**Comment by ll11l1lIllIl1lll** [comment]
Ur dad ran away when ur mom was pregnant xd

**Comment by ll11l1lIllIl1lll** [comment]
You look at the color of your skin and then look at the color of your mother's skin

**Comment by ll11l1lIllIl1lll** [comment]
Have you ever eaten KFC?

**Comment by ll11l1lIllIl1lll** [comment]
are the people in your country friendly towards nig

**Comment by ll11l1lIllIl1lll** [comment]
[**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1034053694 "2022-02-09T18:12:08Z - Replied by Github Reply Comments"):
> btw [https://www.youtube.com/watch?v=YeFzeNAHEhU](https://www.youtube.com/watch?v=YeFzeNAHEhU) [@funcxt](https://github.com/funcxt) [@xiguagege](https://github.com/xiguagege) [@liulihaocai](https://github.com/liulihaocai) you must watch this

everyone knows.

**Comment by ll11l1lIllIl1lll** [comment]
so do you want to know what happened in your country before?

**Comment by ll11l1lIllIl1lll** [comment]
so do you know what happened in your country before

**Comment by SakurajimaMai02** [comment]
> also taiwan is an independant country, gona cry?
> 
> ![](https://camo.githubusercontent.com/c670c42b665f8029e21d650349974113d6fc07fee792c960ffbdbc55b3aeef62/68747470733a2f2f7777772e676f6f676c652e636f6d2f6d6170732f76742f646174613d6f7a73477645684744466f57377a337a45706835477543517854357861553737446a7a4847384d51494530784953446e7171723876726b51765843793864524f417a426e7975546747335552665575425074344365684637713277504b53553364457873504856624b65344b6543673537453163564678377630756d593568467954564b797667484338494e5331496f753659724c48713454714548743771455967344f7656726f7271476d336b566d437974766b35564a6430614b566f34726f515766546d3577316967354e6675765f356e3875423666525970487452462d7164347175574c48797a6176776667)
ur mom is sucking bidens cock and her little pussy is getting wet lol

**Comment by SakurajimaMai02** [comment]
> also taiwan is an independant country, gona cry?
> 
> ![](https://camo.githubusercontent.com/c670c42b665f8029e21d650349974113d6fc07fee792c960ffbdbc55b3aeef62/68747470733a2f2f7777772e676f6f676c652e636f6d2f6d6170732f76742f646174613d6f7a73477645684744466f57377a337a45706835477543517854357861553737446a7a4847384d51494530784953446e7171723876726b51765843793864524f417a426e7975546747335552665575425074344365684637713277504b53553364457873504856624b65344b6543673537453163564678377630756d593568467954564b797667484338494e5331496f753659724c48713454714548743771455967344f7656726f7271476d336b566d437974766b35564a6430614b566f34726f515766546d3577316967354e6675765f356e3875423666525970487452462d7164347175574c48797a6176776667)

ur mom is sucking bidens cock and her little pussy is getting wet lol

**Comment by SakurajimaMai02** [comment]
> also taiwan is an independant country, gona cry?
> 
> ![](https://camo.githubusercontent.com/c670c42b665f8029e21d650349974113d6fc07fee792c960ffbdbc55b3aeef62/68747470733a2f2f7777772e676f6f676c652e636f6d2f6d6170732f76742f646174613d6f7a73477645684744466f57377a337a45706835477543517854357861553737446a7a4847384d51494530784953446e7171723876726b51765843793864524f417a426e7975546747335552665575425074344365684637713277504b53553364457873504856624b65344b6543673537453163564678377630756d593568467954564b797667484338494e5331496f753659724c48713454714548743771455967344f7656726f7271476d336b566d437974766b35564a6430614b566f34726f515766546d3577316967354e6675765f356e3875423666525970487452462d7164347175574c48797a6176776667)

ur a poor flunky of capitalism

**Comment by Chem2080** [comment]
Someone still lives in Republic of Gina.
![Screenshot_2022-02-05-16-55-44-04](https://user-images.githubusercontent.com/69333371/153386207-b8d1e27f-a21c-4308-a2f4-9a70cbea0de1.jpg)

**Comment by Chem2080** [comment]
> i hate the ccp btw ![man standing in front of a tank](https://camo.githubusercontent.com/d23d13b746e466f85eec30f8de8387d7904f25fa62695323146ac29fa651d28a/68747470733a2f2f7777772e686973746f72792e636f6d2f2e696d6167652f635f66697425324363735f73726762253243666c5f70726f6772657373697665253243715f6175746f3a676f6f64253243775f3632302f4d5455334f54497a4e5463354d4463314f5459794e5445302f77686f2d7761732d7468652d74616e6b2d6d616e2d6f662d7469616e616e6d656e2d737175617265732d66656174757265642d70686f746f2e6a7067)

Do you still live in ROG？
![Uploading Screenshot_2022-02-05-16-55-44-04.jpg…]()

**Comment by danik4985** [comment]
> are the people in your country friendly towards nig

are the people in your country friendly towards those who want freedom?

**Comment by danik4985** [comment]
> oh i forget you are the fatherless guy XD

oh wow how original

**Comment by danik4985** [comment]
srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring

**Comment by danik4985** [comment]
> [**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1034053694 "2022-02-09T18:12:08Z - Replied by Github Reply Comments"):
> > btw [https://www.youtube.com/watch?v=YeFzeNAHEhU](https://www.youtube.com/watch?v=YeFzeNAHEhU) [@funcxt](https://github.com/funcxt) [@xiguagege](https://github.com/xiguagege) [@liulihaocai](https://github.com/liulihaocai) you must watch this
> 
> everyone knows.

what about the other video i sent?

**Comment by ll11l1lIllIl1lll** [comment]
[**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1035224856 "2022-02-10T17:44:32Z - Replied by Github Reply Comments"):
> > are the people in your country friendly towards nig
> 
> are the people in your country friendly towards those who want freedom?

what is "freedom" you want

**Comment by ll11l1lIllIl1lll** [comment]
[**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1035231099 "2022-02-10T17:49:17Z - Replied by Github Reply Comments"):
> > [**@danik4985**](https://github.com/danik4985) commented on [](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1034053694 "2022-02-09T18:12:08Z - Replied by Github Reply Comments"):
> > 
> > > btw [https://www.youtube.com/watch?v=YeFzeNAHEhU](https://www.youtube.com/watch?v=YeFzeNAHEhU) [@funcxt](https://github.com/funcxt) [@xiguagege](https://github.com/xiguagege) [@liulihaocai](https://github.com/liulihaocai) you must watch this
> > 
> > everyone knows.
> 
> what about the other video i sent?

1989, Tank man

**Comment by ll11l1lIllIl1lll** [comment]
[**@danik4985**](https://github.com/danik4985) commented on [2022年2月11日 上午1:44 [GMT+8]](https://github.com/UnlegitMC/FDPClient/issues/1146#issuecomment-1035224856 "2022-02-10T17:44:32Z - Replied by Github Reply Comments"):
> > are the people in your country friendly towards nig
> 
> are the people in your country friendly towards those who want freedom?

are you free

**Comment by ll11l1lIllIl1lll** [comment]
What are your actions that reflect your freedom?

**Comment by ll11l1lIllIl1lll** [comment]
can you explain what "democracy" is

**Comment by ll11l1lIllIl1lll** [comment]
just send everything you want send

**Comment by ll11l1lIllIl1lll** [comment]
you'd better look first at how much freedom blacks have in your country

**Comment by SakurajimaMai02** [comment]
> the chinese kinda coping ngl

ur just a joker. Nobody cares

**Comment by SakurajimaMai02** [comment]
> srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring

ur Real life submissive and sucking ur dad cock everyday

**Comment by SakurajimaMai02** [comment]
> srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring

ur mom gangraped by bums everyday and what u can only do is said _oh i hate ccg_ online

> > oh i forget you are the fatherless guy XD
> 
> oh wow how original

ur mom gangraped by bums everyday and what u can only do is said _oh i hate ccg_ online

**Comment by SakurajimaMai02** [comment]
> srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring

poor dog

**Comment by danik4985** [comment]
where do you get your insults from? 3rd grade?

**Comment by danik4985** [comment]
@SakurajimaMai02 you a member of the ccp?

**Comment by danik4985** [comment]
> > srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring
> 
> ur Real life submissive and sucking ur dad cock everyday

wait a minute didnt one of your comrades call me "fatherless"? at least get your stories straight

**Comment by SakurajimaMai02** [comment]
> @SakurajimaMai02 you a member of the ccp?



> > > srsly @ll11l1lIllIl1lll be more creative your "insults" are incredibly boring
> > 
> > 
> > ur Real life submissive and sucking ur dad cock everyday
> 
> wait a minute didnt one of your comrades call me "fatherless"? at least get your stories straight

sadly  its ur stepfather lmao

**Comment by danik4985** [comment]
zamn
