### ISSUE TITLE
What custom huds do you recommend and how do i install them?

### ISSUE THREAD

**Issue by Arjun-Bhatnagar** [UnlegitMC/FDPClient#116]

**Comment by BobIsMyManager** [comment]
Use this custom build

**Comment by ll11l1lIllIl1lll** [comment]
Default hud
if you want install a hud : overwrite the hud.json you want to mcDataDir/FDPClient-1.8/hud.json

**Comment by liulihaocai** [comment]
use the default hud in latest version xd
