### ISSUE TITLE
Why does fdp client take long to open than other clients 

### ISSUE THREAD

**Issue by NotDevilhunter** [UnlegitMC/FDPClient#1164]

**Comment by liulihaocai** [comment]
i think fdp client just takes normal speed than other clients

**Comment by liulihaocai** [comment]
but if really slower starts up cuz we have fps optimizes, https://github.com/UnlegitMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/injection/transformers/OptimizeTransformer.java
and it maybe takes sometime to transform the classes
