### ISSUE TITLE
FDP cannot run in original launcher

### ISSUE THREAD

**Issue by zyeexd** [UnlegitMC/FDPClient#1172]
Hi, when i try to open forge with FDP i have this error 
![image](https://user-images.githubusercontent.com/90262547/154801402-33a6ea3d-efa7-452a-8895-b36373c8b1c4.png)

**Comment by guimc233** [comment]
Open INFO

**Comment by guimc233** [comment]
Open info log display

**Comment by zyeexd** [comment]
This is all + Info log https://paste.gg/p/anonymous/b285405b9fa94fcdbe3b1b75fa7a92ff

**Comment by guimc233** [comment]
Open .minecraft/logs, upload latest.log

**Comment by zyeexd** [comment]
[latest.log](https://github.com/UnlegitMC/FDPClient/files/8102233/latest.log)

**Comment by guimc233** [comment]
or try other launcher

**Comment by zyeexd** [comment]
im uploading the log

**Comment by zyeexd** [comment]
When i open the game the log isnt the last i mean it doesnt update

**Comment by guimc233** [comment]
> When i open the game the log isnt the last i mean it doesnt update
> 

Try other launcher like gdlauncher

**Comment by zyeexd** [comment]
[latest.log](https://github.com/UnlegitMC/FDPClient/files/8102239/latest.log)
this is the correct log

**Comment by guimc233** [comment]
It looks like something failed to load. Did you use the original Minecraft 1.8.9? Or that you are using the incorrect version

**Comment by zyeexd** [comment]
i can try another version of forge

**Comment by zyeexd** [comment]
Or what should i try?

**Comment by guimc233** [comment]
> Or what should i try?

i think there is something wrong with your client.
u can try other launcher.

**Comment by zyeexd** [comment]
> > Or what should i try?
> 
> i think there is something wrong with your client. u can try other launcher.

i have tlauncher its ok?

**Comment by zyeexd** [comment]
> > Or what should i try?
> 
> i think there is something wrong with your client. u can try other launcher.

i can try tlauncher is that ok?

**Comment by guimc233** [comment]
> > > Or what should i try?
> > 
> > i think there is something wrong with your client. u can try other launcher.
> 
> i can try tlauncher is that ok?
> 

any launcher

**Comment by zyeexd** [comment]
Oh, thanks it works with tlauncher, but i can fix my original launcher?

**Comment by guimc233** [comment]
> Oh, thanks it works with tlauncher, but i can fix my original launcher?
> 

idk

**Comment by guimc233** [comment]
> Oh, thanks it works with tlauncher, but i can fix my original launcher?
> 

idk. im not using original launcher

**Comment by AlexBartles2012** [comment]
> Oh, thanks it works with tlauncher, but i can fix my original launcher?

are you putting -Dfdp-legacy-ui in the JVM Arguments? because that fixed the latest version
