### ISSUE TITLE
How to start up the launcher

### ISSUE THREAD

**Issue by RxbuXst** [UnlegitMC/FDPClient#1179]
I'm quite confused how to start up the launcher its self, I don't get how to download it and make it work, help?

**Comment by F3D7P6hxg** [comment]
First,download forge 1.89 version,install forge to your minecraft launcher.Then,download fdp client at https://getfdp.today/ or https://getfdp.today/eap.html (beta version).it will show in zip file,pls extract the fdpclient zip file then move the jar into your .minecraft mods folder.

**Comment by F3D7P6hxg** [comment]
btw you can use optifine 1.89 with fdpclient

**Comment by llama-for3ver** [comment]
😐
