### ISSUE TITLE
fdpclient unable start

### ISSUE THREAD

**Issue by LingLing1301** [UnlegitMC/FDPClient#1184]
[crash-2022-02-23_17.01.59-client.txt](https://github.com/UnlegitMC/FDPClient/files/8123076/crash-2022-02-23_17.01.59-client.txt)
fdpclient unable start,crashing while loading

**Comment by HowardZHY** [comment]
same
[fml-client-2.log](https://github.com/UnlegitMC/FDPClient/files/8192925/fml-client-2.log)

**Comment by HowardZHY** [comment]
still on 3.0.0
[crash-2022-03-07_00.04.25-client.txt](https://github.com/UnlegitMC/FDPClient/files/8192962/crash-2022-03-07_00.04.25-client.txt)

**Comment by WindLeaf233** [comment]
hey try this #433
