### ISSUE TITLE
Labymod

### ISSUE THREAD

**Issue by i7vlo** [UnlegitMC/FDPClient#1185]
FDP client not working with labymod im using
this version : [44c9d6c] (https://github.com/UnlegitMC/FDPClient/commit/44c9d6c71178aa09c543d242776a661d5961c86a)
plz fix it 😢

**Comment by i7vlo** [comment]
this is last version

**Comment by llama-for3ver** [comment]
please
fdp
with labymod

**Comment by contionability** [comment]
Why u want to use fdp with labymod bruh
it detects hack mods

**Comment by i7vlo** [comment]
in blocksmc redstonepvp we need labymod :(
