### ISSUE TITLE
It just Keeps Crashing

### ISSUE THREAD

**Issue by sammyisnotavilable** [UnlegitMC/FDPClient#1195]
i downloaded the mod
made 1.8.9 forge runner thing whatever (on curseforge)
im on mac thats probs the problem
I press play on curseforge
goes on launcher
i press play
then says this

ERROR
Game Crashed

An unexpected issue occured that the game has crashed. We're sorry for the inconvenience.

This Crash may be caused by an invalid Java Runtime Configuration. Check any custom configuration settings.

Exit Code: 1

**Comment by anbuchicken** [comment]
Same here But I am on window 10 and On the real Minecraft here is a sreenshot
![Minecraft Launcher 3_6_2022 7_01_26 AM](https://user-images.githubusercontent.com/101047041/156922259-5fd7f09e-27d4-4fd8-ba7d-86a97c255faf.png)

**Comment by HowardZHY** [comment]
log?
