### ISSUE TITLE
[Bug] i can`t join servers

### ISSUE THREAD

**Issue by clone12345** [UnlegitMC/FDPClient#1198]
i cant join server but i can play sigleplayer

1. multiplayer page
2. join random server
3. :>

**Expected behavior**
joining server

**Screenshots**
![Zrzut ekranu 2022-03-02 223026](https://user-images.githubusercontent.com/84021149/156453471-3b74e2bf-a05c-4582-a1f7-88b734b4c26f.png)
https://imgur.com/a/Bb6GnaB

**Comment by WannaCry1LoL** [comment]
Ur dumb
First off your name has special characters (you logged in with an email as your name)
Second off your name is too long
