### ISSUE TITLE
[Bug] <Title Here>

### ISSUE THREAD

**Issue by craciu25yt** [UnlegitMC/FDPClient#1201]
When login with mcleaks using ms@CJgPmCEQjg6Vpn5G it crash

**Comment by F3D7P6hxg** [comment]
use direct login,paste your alt token and key random password...you need mcleaks authenticator too.
also mcleaks maybe a virus,it automatic install unknown software to your pc,so becareful

**Comment by HowardZHY** [comment]
need more info

**Comment by craciu25yt** [comment]
I used authenticator and it don't worked
