### ISSUE TITLE
Spelling error when loading a config that does not exist

### ISSUE THREAD

**Issue by NOAHBENJ** [UnlegitMC/FDPClient#1202]
![Screen Shot 2022-03-06 at 8 39 14 pm](https://user-images.githubusercontent.com/82064301/156917634-848edf44-c85c-4119-9dd1-196f6032dfec.png)

**Comment by F3D7P6hxg** [comment]
change your config to another name might works

**Comment by contionability** [comment]
@F3D7P6hxg read the title
@NOAHBENJ corrected
