### ISSUE TITLE
FDP 3.0.0 Crashes

### ISSUE THREAD

**Issue by AiKk291** [UnlegitMC/FDPClient#1209]
How to fix fdp 3.0 Crashes?

**Comment by 3000IQPlay** [comment]
> cannot fix without a log

Disable menu background in config file

**Comment by Hop2full** [comment]
My fdp client crashes when i click on legacy ui i use tlauncher help

**Comment by HowardZHY** [comment]
FDP needs a issue cleanup.
all 3.0.0 issues without a log should be closed.
