### ISSUE TITLE
FDP Client early access build git-ae473aa<Title Here>

### ISSUE THREAD

**Issue by saiprajeet** [UnlegitMC/FDPClient#1214]
Dude my FDP client keeps crashing since i upgraded to git-ae473aa from 2.0.0, when i join a server or join a singleplayer world,
I deleted my FDP client folder of 2.0.0,
anyone can help me fix this?
![image](https://user-images.githubusercontent.com/86559108/157381016-80e1b844-d6f9-415d-9067-3deb36bcf9b6.png)

**Comment by minhlongdev** [comment]
same

**Comment by Abhinand1885** [comment]
Failed to download file.
Name: 1.8.json
URL: https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json
Error details: HTTP server doesn't seem to support byte ranges. Cannot resume.
Filename on disk: 1.8.json
Path: C:\Users\youra$$\AppData\Roaming\.minecraft\assets\indexes\1.8.json
Exists: File
is this your crash thing?

**Comment by minhlongdev** [comment]
no
