### ISSUE TITLE
Could not determine the dependencies of task ':runClient'. > Resolving dependency configuration 'runtimeOnly' is not allowed as it is defined as 'canBeResolved=false'.   Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'runtimeOnly' should be resolved.  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### ISSUE THREAD

**Issue by SUNDYT** [UnlegitMC/FDPClient#1231]
Could not determine the dependencies of task ':runClient'.
> Resolving dependency configuration 'runtimeOnly' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'runtimeOnly' should be resolved.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

HOW TO FIX THIS???

**Comment by HowardZHY** [comment]
no full log

**Comment by SUNDYT** [comment]
No this is full log


вс, 3 апр. 2022 г., 23:09 Howard ZHY ***@***.***>:

**Comment by SUNDYT** [comment]
This is Itelj IDEA

**Comment by SUNDYT** [comment]
This is sources
