### ISSUE TITLE
启动时崩溃 java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-9,5,main] already has the context current

### ISSUE THREAD

**Issue by HowardZHY** [UnlegitMC/FDPClient#1232]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The game crashed when loading
java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-9,5,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**To Reproduce**
only Forge and FDP

**Expected behavior**
launch without crash

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.
[crash-2022-03-16_13.47.53-client.txt](https://github.com/UnlegitMC/FDPClient/files/8259240/crash-2022-03-16_13.47.53-client.txt)
[fml-client-latest.log](https://github.com/UnlegitMC/FDPClient/files/8259250/fml-client-latest.log)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 3.0.0

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
null

**Additional info**
<Add any other context about the problem here.>

**Comment by WindLeaf233** [comment]
#433

**Comment by HowardZHY** [comment]
> #433

没用,还是崩

**Comment by HowardZHY** [comment]
Is there a no fancy background/gui (vanilla-style) version of FDP ?



At 2022-04-07 18:27:33, "ImXiaoChen" ***@***.***> wrote:

crash-2022-04-07_18.17.40-client.txt
@HowardZHY
So do I.
@WindLeaf233
The method you provided didn't work.

**Comment by Networs** [comment]
> Is there a no fancy background/gui (vanilla-style) version of FDP ? At 2022-04-07 18:27:33, "ImXiaoChen" ***@***.***> wrote: crash-2022-04-07_18.17.40-client.txt @HowardZHY So do I. @WindLeaf233 The method you provided didn't work. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Strangely, I set the enabled option in ". Minecraft / Version / XX (this is the version name I use) / config / splash. Properties" to "enabled = false". Then I restarted the client, still displayed a fancy loading screen after startup, and then it crashed again
Postscript: I reopened "splash. Properties" and found that the enabled option was still false

**Comment by Networs** [comment]
你也是中国人？XD我刚发现qwq
我的问题就是按照枫叶那个设置了，但是无效，仍然崩溃

**Comment by HowardZHY** [comment]
看看隔壁wurst,没有花哨的界面自然就不会崩



在 2022-04-08 13:57:55，"ImXiaoChen" ***@***.***> 写道：

你也是中国人？XD我刚发现qwq
我的问题就是按照枫叶那个设置了，但是无效，仍然崩溃

**Comment by HowardZHY** [comment]
我更新过显卡驱动了
我连FDP文件夹都没生成



在 2022-04-08 20:31:28，"ImXiaoChen" ***@***.***> 写道：

我解决了，解决办法大概是
1.按照枫叶提供的方法先禁用掉，图的就是保险
2.安装windows Visual x64运行库（因为我电脑是64位的haha）
3.能更新驱动更新驱动，反正我没更新:D
4.换PCL为HMCL
5.不要使用他人的文件夹配置，可能会导致初始化错误，建议让它自己生成
6.更新JAVA为最新的8u321版本

如果仍不能解决我无能为力了=w=，我按照上述步骤才能启动的

最后，开*适当，开心就好XD
