### ISSUE TITLE
[feature] MultiConnect

### ISSUE THREAD

**Issue by Soulplexis** [UnlegitMC/FDPClient#1237]
Hi im playing on a offline server. is it possible to add a module which will connect 5 other offline-accounts but on my same client. i want to do a in-sync moving or maybe stress test. in other words I go on the server with my regular username and while im on the client will send 5 fake logins to the server

**Comment by HowardZHY** [comment]
Try console client

**Comment by horanDEV** [comment]
i think it can be in SilentDisconnect

**Comment by liulihaocai** [comment]
try [go-mc](https://github.com/Tnze/go-mc) or [MCProtocolLib](https://github.com/GeyserMC/MCProtocolLib)
