### ISSUE TITLE
FDPClient latest BUILD FAILED

### ISSUE THREAD

**Issue by FDPUser443** [UnlegitMC/FDPClient#1238]
C:\Users\Admin\Downloads\FDPClient-main>gradlew build
    ...
> Task :generateGitProperties FAILED
:generateGitProperties (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.004 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGitProperties'.
> No Git repository found.

--- ================== ---
C:\Users\Admin\Downloads\FDPClient-main>gradlew generateGitProperties --info
Initialized native services in: C:\Users\Admin\.gradle\native
Found daemon DaemonInfo{pid=5812, address=[4c70cc84-9aad-4742-ab93-74836423f9cb port:49858, addresses:[/127.0.0.1]], state=Idle, lastBusy=1647675685405, context=DefaultDaemonContext[uid=5103462c-1523-48c1-b6c9-d46149f443b6,javaHome=D:\Java\jdk,daemonRegistryDir=C:\Users\Admin\.gradle\daemon,pid=5812,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx3g,-Dfile.encoding=windows-1251,-Duser.country=RU,-Duser.language=ru,-Duser.variant]} however its context does not match the desired criteria.
At least one daemon option is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=D:\Java\jdk,daemonRegistryDir=C:\Users\Admin\.gradle\daemon,pid=540,idleTimeout=null,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1251,-Duser.country=RU,-Duser.language=ru,-Duser.variant]
Actual: DefaultDaemonContext[uid=5103462c-1523-48c1-b6c9-d46149f443b6,javaHome=D:\Java\jdk,daemonRegistryDir=C:\Users\Admin\.gradle\daemon,pid=5812,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx3g,-Dfile.encoding=windows-1251,-Duser.country=RU,-Duser.language=ru,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 2608). The daemon log file: C:\Users\Admin\.gradle\daemon\6.9.1\daemon-2608.out.log
Starting 6th build in daemon [uptime: 32 mins 57.911 secs, performance: 100%, GC rate: 0,01/s, heap usage: 9% of 341.5 MiB, non-heap usage: 32% of 256 MiB]
Using 2 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file 'C:\Users\Admin\Downloads\FDPClient-main\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\Admin\Downloads\FDPClient-main\build.gradle'.
Included projects: [root project 'FDPClient']

> Configure project :
Evaluating root project 'FDPClient' using build file 'C:\Users\Admin\Downloads\FDPClient-main\build.gradle'.
kotlin scripting plugin: created the scripting discovery configuration: kotlinScriptDef
kotlin scripting plugin: created the scripting discovery configuration: testKotlinScriptDef
kotlin scripting plugin: created the scripting discovery configuration: apiKotlinScriptDef
file or directory 'C:\Users\Admin\Downloads\FDPClient-main\build\depAts', not found
file or directory 'C:\Users\Admin\Downloads\FDPClient-main\src\api\resources', not found
Found an AccessTransformer: fdpclient_at.cfg
Adding source set 'main' to mixin processor
Adding source set 'main' to mixin processor
All projects evaluated.
Selected primary task 'generateGitProperties' from project :
Tasks to be executed: [task ':generateGitProperties']
Tasks that were excluded: []
:generateGitProperties (Thread[Daemon worker Thread 5,5,main]) started.

> Task :generateGitProperties FAILED
:generateGitProperties (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.015 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGitProperties'.
> No Git repository found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
1 actionable task: 1 executed
<-------------> 0% WAITING
> IDLE

**Comment by LoserFox** [comment]
fork and use git clone

**Comment by FDPUser443** [comment]
Thanks a lot!
