### ISSUE TITLE
[Bug] Vince is not a FDP Dev

### ISSUE THREAD

**Issue by dev-vince** [UnlegitMC/FDPClient#1244]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Vince is not a developer of the free client FDP

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. You check FDP on github
2. You see vince is not a dev :(
3. 
4. 

**Expected behavior**
FDP will be a shit client 

**To fix**
1.) Dm Vince#7777 and make him FDP dev
2.) Go to github and invite dev-vince to the FDP repo.

**Why you should fix this issue**
FDP will become sexy

**Screenshots/Video**

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by Internalol** [comment]
do this

**Comment by K1lez** [comment]
Yeah, this is a huge bulge!
bug*

**Comment by Body-Alhoha** [comment]
Biggest bug i ever seen of fdp 1!!11!1!

**Comment by DivineEnergylol** [comment]
make him dev or delete the repository as there will be no future

**Comment by ignSKRRRTT** [comment]
on god bruh

**Comment by Qoft** [comment]
do this ^^^

**Comment by odeyity** [comment]
yes do this

**Comment by Astomero** [comment]
pls become fdp dev
