### ISSUE TITLE
ProphuntESP?

### ISSUE THREAD

**Issue by MinecraftHDKIll** [UnlegitMC/FDPClient#125]
ProphuntESP module?

**Comment by ll11l1lIllIl1lll** [comment]
What is ProphuntESP

**Comment by Chamzis** [comment]
> What is ProphuntESP

ProphuntESP is an ESP that only renders people that are blocks in prophunt/Hide n' seek

**Comment by liulihaocai** [comment]
maybe add

**Comment by MinecraftHDKIll** [comment]
yeah thats in liquidbounce so idk
