### ISSUE TITLE
my fdp is broke

### ISSUE THREAD

**Issue by snowfox0518** [UnlegitMC/FDPClient#135]
my fdp wasn't open when i'm using PCL2 launcher
翻译:lz的fdp端不能在PCL2打开

**Comment by liulihaocai** [comment]
是的，就是不能打开

**Comment by ll11l1lIllIl1lll** [comment]
IQ BRO

**Comment by shuhai2008** [comment]
你好！PCL2启动器并不在我们支持的启动器列表中！
你可以尝试使用其他启动器，例如GDL或者HMCL(https://github.com/huanghongxun/HMCL)
PCL2启动器启动FDP客户端的相关问题可以查看我们的另外一个FUCKPCL项目。
祝您生活愉快，万事如意。

**Comment by shuhai2008** [comment]
你好！PCL2启动器并不在我们支持的启动器列表中！
你可以尝试使用其他启动器，例如GDL或者HMCL(https://github.com/huanghongxun/HMCL)
PCL2启动器启动FDP客户端的相关问题可以查看我们的另外一个FUCKPCL项目。
祝您生活愉快，万事如意。
