### ISSUE TITLE
需要帮助

### ISSUE THREAD

**Issue by DozerFFFFFF** [UnlegitMC/FDPClient#149]
我用任何
启动器都无法启动FDP？？：？？？？？（非PCL)
MultiMC：![image](https://user-images.githubusercontent.com/89580754/130947602-1d0d7ef5-8897-40c4-8558-fe5b84cb9a63.png)
HMCL：
![image](https://user-images.githubusercontent.com/89580754/130948046-c5c3969e-7e15-4567-ade8-29ac27dc78bb.png)

**Comment by DozerFFFFFF** [comment]
> 这个报错不是因为启动器类型引起的，是因为FDP使用的新UI引擎

大佬那我怎么才能正常使用它？

**Comment by shuhai2008** [comment]
> > 这个报错不是因为启动器类型引起的，是因为FDP使用的新UI引擎
> 
> 大佬那我怎么才能正常使用它？

新版本的fdp有些兼容性问题，如果并不着急可以回到1.3.3版本

**Comment by DozerFFFFFF** [comment]
> > > 这个报错不是因为启动器类型引起的，是因为FDP使用的新UI引擎
> > 
> > 
> > 大佬那我怎么才能正常使用它？
> 
> 新版本的fdp有些兼容性问题，如果并不着急可以回到1.3.3版本

![image](https://user-images.githubusercontent.com/89580754/131211773-6f2954c8-6ffc-4bd2-8668-87f7234c7e7a.png)
![image](https://user-images.githubusercontent.com/89580754/131211791-93d9cbb3-71f3-4902-b0e2-a5043b308773.png)
它仍然无法运行（v1.3.3）

**Comment by liulihaocai** [comment]
> Try to recover to version 1.3.3 without ultralight
> https://github.com/UnlegitMC/FDPClient/releases/tag/v1.3.3

hey v1.4.0 dont have ultralight too
