### ISSUE TITLE
Work with CheaterMC's FDPClient

### ISSUE THREAD

**Issue by gabrielvicenteYT** [UnlegitMC/FDPClient#170]
It has MANY useful features that will help FDPClient 2.0. UltraLight-only FDPClient is stupid. Re-add old clickgui please...
I'm the main dev of FDPClient 2.0.

**Comment by ll11l1lIllIl1lll** [comment]
> Unless ultralight operation fails, no one will think so

**new clickgui = FPS-=500**

**Comment by liulihaocai** [comment]
i think it will be works
