### ISSUE TITLE
Error "ui_resource.zip"

### ISSUE THREAD

**Issue by zWTbz** [UnlegitMC/FDPClient#171]
Caused by: java.lang.IllegalStateException: UltralightEngine::class.…tream("ui_resources.zip") must not be null

[error.txt](https://github.com/UnlegitMC/FDPClient/files/7064989/error.txt)

**Comment by zWTbz** [comment]
> When will this happen?

i try to setting up new workspace same error

**Comment by liulihaocai** [comment]
run client have some issues plz copy the file into the page folder or output the mod jar and run it in forge
