### ISSUE TITLE
<suggestion>add blocksmc staff detector(autoleave when a staff join a game)

### ISSUE THREAD

**Issue by F3D7P6hxg** [UnlegitMC/FDPClient#1729]
Pls add this and it will be very cool

**Comment by negroshooter991** [comment]
they cant because they dont know who is a admin

**Comment by negroshooter991** [comment]
they dont know anything about the staff or mods so they cant.

**Comment by F3D7P6hxg** [comment]
dev can just check liquidbounce plus source code they have staff detector for blocksmc which is call antiban module
