### ISSUE TITLE
opZywl 我看你就是个BUG

### ISSUE THREAD

**Issue by VeibaeMCC** [UnlegitMC/FDPClient#187]
凡是你构建的FDP没有不崩溃的时候，我因为你损失了69份配置和19个服务器ip存档，你就差帮我把我的windows10都干成废铁了

**Comment by opZywl** [comment]
HAHAHA CRY

**Comment by fdpmc** [comment]
sir this is a  minecraft hacked client, not mental help nor is it tech support
