### ISSUE TITLE
Dear dev,pls dont be lazy to update bypass

### ISSUE THREAD

**Issue by F3D7P6hxg** [UnlegitMC/FDPClient#1903]
add verus critical and killaura autoclicker which bypass vulcan and to be honest your killaura autoclicker flag aac matrix verus and vulcan so pls make it better.remove useless verus fly which cant bypass verus already and add verus damage fly go fcking test your verus bypass at verusallah.mine.fun(verus test server)and just make this client better pls.

**Comment by Arcadius159** [comment]
Config issue

**Comment by contionability** [comment]
Config issue
also, I'm senior 3 student so I can only update monthly :(
ask @liulihaocai for more bypasses :lol:

**Comment by minhlongdev** [comment]
wait i think i met u ingame
