### ISSUE TITLE
fdp not working

### ISSUE THREAD

**Issue by nickonick1** [UnlegitMC/FDPClient#1934]
i put fdp client in the mods folder and launch 1.8.9 forge THE FDP MOD DONT RUN IT DON'T WORK THE FDP CLIENT IS IN THE FOLDER
Like do i need to change java version or what?

**Comment by nickonick1** [comment]
![image](https://user-images.githubusercontent.com/99060505/162360342-4453fceb-e6dd-4108-8d15-96ec3f301601.png)

**Comment by nickonick1** [comment]
![image](https://user-images.githubusercontent.com/99060505/162360410-dfe81556-f117-411e-8028-b487918b1ee0.png)

**Comment by HowardZHY** [comment]
No log - invalid

**Comment by nickonick1** [comment]
> No log - invalid

here is the lastest log 
[latest.log](https://github.com/UnlegitMC/FDPClient/files/8451938/latest.log)

**Comment by HowardZHY** [comment]
u have a corrupt jar
use the latest build on getfdp.today



At 2022-04-08 20:50:10, "nickonick1" ***@***.***> wrote:

No log - invalid

here is the lastest log
latest.log
