### ISSUE TITLE
SuperKnockback doesnt work

### ISSUE THREAD

**Issue by OrdinaryHacker** [UnlegitMC/FDPClient#1960]
doesnt do anything but worked in older versions I think its broken since 3.0 
It worked on 2.1 and I think 2.2 too but im not sure.
correction: it doesnt work when "nopacket" is enabled in sprint module

**Comment by contionability** [comment]
NoPacket will cancel all sprint packet so it doesn't work bruh

**Comment by OrdinaryHacker** [comment]
Yes that makes sense, is there a way to use nopacket sprint with superknockback ?

**Comment by contionability** [comment]
just don't use nopacket mode
(is there any anticheat can be bypassed by nopacket mode? wired)

**Comment by OrdinaryHacker** [comment]
no packet mode bypass matrix all dir. sprint and also you can bhop backwards and makes strafing around targets less flagging on jartex/pika
