### ISSUE TITLE
关于我对FDP的反馈

### ISSUE THREAD

**Issue by yy666245yy** [UnlegitMC/FDPClient#1961]
关于我对FDP的反馈：
1.动画模块里的“Swong”模式希望可以改进（当然抄其他客户端的更好）；
2.Noti模块可以去掉文字阴影，然后让用户自定义文字颜色（当然你加个图标会更不错！）；
3.关于模块显示文字阴影的问题，我觉得可以仿照Noteless的文字阴影（因为太好看了）；
4.就是动画的改进，例如Noti模块的动画，看上去很拖拉，希望是等进度条走完了再快速退出界面比较好；
5.渲染问题，但我开启"Scaffold"模块时，字体会变粗；
6.同样的问题，Blur模块希望能改进，不然看着怪难受的；
7.希望模块显示栏能增加一个“Astolfo”的配色；
8.希望你能做到以上7点：
![error](https://user-images.githubusercontent.com/88182962/166102524-bcf578cb-e294-4d1e-94de-70a242084664.png)
![warning](https://user-images.githubusercontent.com/88182962/166102529-dc8f6fe6-0918-44a8-a1d6-0c02c98528e3.png)
![info](https://user-images.githubusercontent.com/88182962/166102531-c3aa5a21-030f-4f17-a164-c448607d22ad.png)
![checkmark](https://user-images.githubusercontent.com/88182962/166102532-766a28fc-daf4-474a-b0e5-45e04b438fdb.png)
D
9.如果你能在Noti上加图标，附加文件里有我的图标哦¬

**Comment by contionability** [comment]
琉璃退了，Visual都是她写的
不过这东西等我学学
未来会改进的

**Comment by yy666245yy** [comment]
嗯！相信FDP

**Comment by VeibaeMCC** [comment]
我神马anticheat的bypass都不会code，但我喜欢code关于visual的code，或许我可以捣鼓捣鼓
