### ISSUE TITLE
Ultralight cause JVM crash after a click

### ISSUE THREAD

**Issue by THEKEMER** [UnlegitMC/FDPClient#205]
Hi, I have a problem with a new client update where a new ClickGui was added to me when I opened it and, for example, I opened the Combat drop-in game crash 
Please help me

**Comment by liulihaocai** [comment]
we found that issue on some PCs too, we are also trying to fix it

**Comment by liulihaocai** [comment]
we will combine no-ultralight branch and ultralight branch to make users who cannot use ultralight can use new bypass features

**Comment by THEKEMER** [comment]
ok 
thanks

**Comment by liulihaocai** [comment]
#458
