### ISSUE TITLE
Can't Update

### ISSUE THREAD

**Issue by ThanhMinecraftVN123** [UnlegitMC/FDPClient#211]
Why  i can't upgrade fdp v1.4.0 to 1.4.0updatefix ?

**Comment by KoqKay** [comment]
You actually upgraded

**Comment by ThanhMinecraftVN123** [comment]
FDP already has v1.4.0-UPDATEFIX so when I enter the game it says I have ? and I have downloaded the new version but when I restart the game it still asks me if I want to download v1.4.0-UPDATEFIX or not? even though I renamed the file

**Comment by liulihaocai** [comment]
i forgot 2 change version inside the client sry
but if u received the update alert = it actually upgraded lol

**Comment by ThanhMinecraftVN123** [comment]
you make me worry, liulihaocai but now i know the reason why when i entered the game i felt fine thank you :))

**Comment by liulihaocai** [comment]
v2 released
