### ISSUE TITLE
曾经最常见的话：FDPClient启动中......  ；  现在最常见的话：  在没有错误日志的情况下诊断任何问题无异于闭眼开车......

### ISSUE THREAD

**Issue by VeibaeMCC** [UnlegitMC/FDPClient#217]
看标题

**Comment by VeibaeMCC** [comment]
######################### FDP CRASH REPORT #########################

If this problem persists, please send this file to the FDPClient developers! Website (where you can join the discord server): http://FDPClient.Club/
This file will be saved in ".minecraft/FDPCrashLogs.txt"

 | 在没有错误日志的情况下诊断任何问题无异于闭眼开车!  --Apache官方文档
 | Troubleshooting any problem without the error log is like driving with your eyes closed.
 | From Apache official documentation Getting Started chapter
   - INFO:
   |   Version: git-ad77ae5
   |   Time: 1655874337188
   |   OS: WINDOWS

######################### FDP CRASH REPORT #########################
---- Minecraft Crash Report ----

WARNING: coremods are present:
  InputFix (InputFix-1.8.x-v2.jar)
  FMLLoadingPlugin (内存溢出修复.jar)
  TransformerLoader (FDPClient-ad77ae5.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 22-6-22 下午1:05
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:721)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:782)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1415)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 7 total; [EntityPlayerSP['Veibae_hKXp7P'/45509, l='MpServer', x=0.50, y=67.00, z=0.50], EntityOtherPlayerMP['saikii'/50982, l='MpServer', x=-2.44, y=66.00, z=-5.16], EntityOtherPlayerMP['bip672'/51248, l='MpServer', x=-1.06, y=67.00, z=-2.06], EntityOtherPlayerMP['§e§l派送员'/124, l='MpServer', x=-5.50, y=67.00, z=-0.50], EntityOtherPlayerMP['Zhouyun'/51260, l='MpServer', x=0.47, y=67.00, z=-2.84], EntityOtherPlayerMP['§e§l新手教程:WiKi'/118, l='MpServer', x=6.50, y=67.00, z=-0.50], EntityOtherPlayerMP['§b永恒帝国'/121, l='MpServer', x=5.50, y=67.00, z=-15.50]]
	Chunk stats: MultiplayerChunkCache: 31, 31
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 22.00,4.00,426.00 - World: (22,4,426), Chunk: (at 6,0,10 in 1,26; contains blocks 16,0,416 to 31,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3185062530 game time, 22723297200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityPlayerSP['Veibae_hKXp7P'/45509, l='MpServer', x=0.50, y=67.00, z=0.50], EntityOtherPlayerMP['saikii'/50982, l='MpServer', x=-2.44, y=66.00, z=-5.16], EntityOtherPlayerMP['bip672'/51248, l='MpServer', x=-1.06, y=67.00, z=-2.06], EntityOtherPlayerMP['§e§l派送员'/124, l='MpServer', x=-5.50, y=67.00, z=-0.50], EntityOtherPlayerMP['Zhouyun'/51260, l='MpServer', x=0.47, y=67.00, z=-2.84], EntityOtherPlayerMP['§e§l新手教程:WiKi'/118, l='MpServer', x=6.50, y=67.00, z=-0.50], EntityOtherPlayerMP['§b永恒帝国'/121, l='MpServer', x=5.50, y=67.00, z=-15.50], EntityOtherPlayerMP['saikii'/50982, l='MpServer', x=-2.44, y=66.00, z=-5.16], EntityItem['item.item.compass'/104, l='MpServer', x=0.50, y=72.14, z=-7.63], EntityArmorStand['Armor Stand'/105, l='MpServer', x=0.50, y=70.88, z=-7.63], EntityArmorStand['Armor Stand'/106, l='MpServer', x=0.50, y=70.34, z=-7.63], EntityArmorStand['§r欢迎您加入 §2Aria §6Craft §e§l国际服'/107, l='MpServer', x=0.50, y=70.09, z=-7.63], EntityArmorStand['§r当您正式进入服务器后，则默认您§a§l同意§r《玩家协议》'/108, l='MpServer', x=0.50, y=69.84, z=-7.63], EntityArmorStand['Armor Stand'/109, l='MpServer', x=0.50, y=69.59, z=-7.63], EntityArmorStand['§a右键§r打开你手上的菜单，若存在疑问请使用客服中心咨询'/110, l='MpServer', x=0.50, y=69.34, z=-7.63], EntityArmorStand['§2Aria §6Craft §e§l国际服 §r玩家交流群: §a695715945'/111, l='MpServer', x=0.50, y=69.09, z=-7.63], EntityOtherPlayerMP['bip672'/51248, l='MpServer', x=-1.06, y=67.00, z=-2.06], EntityArmorStand['Armor Stand'/112, l='MpServer', x=0.50, y=68.84, z=-7.63], EntityItem['item.item.swordDiamond'/113, l='MpServer', x=0.50, y=69.67, z=-7.63], EntityArmorStand['Armor Stand'/114, l='MpServer', x=0.50, y=68.41, z=-7.63], EntityArmorStand['§c§l请勿使用第三方工具作弊，否则将会受到处罚！'/115, l='MpServer', x=0.50, y=67.88, z=-7.63], EntityOtherPlayerMP['§e§l新手教程:WiKi'/118, l='MpServer', x=6.50, y=67.00, z=-0.50], EntityOtherPlayerMP['§b永恒帝国'/121, l='MpServer', x=5.50, y=67.00, z=-15.50], EntityOtherPlayerMP['§e§l派送员'/124, l='MpServer', x=-5.50, y=67.00, z=-0.50], EntityOtherPlayerMP['Zhouyun'/51260, l='MpServer', x=0.47, y=67.00, z=-2.84]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- PandaSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1140106080 bytes (1087 MB) / 1610612736 bytes (1536 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx4095m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	InputFix{1.8.x-v2} [InputFix] (minecraft.jar) 
	Loaded coremods (and transformers): 
InputFix (InputFix-1.8.x-v2.jar)
  lain.mods.inputfix.InputFixTransformer
FMLLoadingPlugin (内存溢出修复.jar)
  io.prplz.memoryfix.ClassTransformer
TransformerLoader (FDPClient-ad77ae5.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5450'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Athlon(tm) II X4 610e Processor

**Comment by cubk** [comment]
请先禁用其他mod

**Comment by Suicidemouse33** [comment]
Stop using FDPClient, start using LiquidBounce with scripts.
