### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dont-doubt** [UnlegitMC/FDPClient#217]
https://github.com/UnlegitMC/FDPClient/blob/671aa12c851e4863fade46421ece205ff033ffa7/ui/src/clickgui.html#L395
Make -> Made, Power -> Powered

current:
`<p style="color: rgba(255, 255, 255, 0.3);position: fixed;bottom: -5px;font-size: 10px;right: 3px;text-align: right;">Make by 2734583@qq.com<br>Power by Material Design<br>Running in FDPClient</p>`

should be:
`<p style="color: rgba(255, 255, 255, 0.3);position: fixed;bottom: -5px;font-size: 10px;right: 3px;text-align: right;">Made by 2734583@qq.com<br>Powered by Material Design<br>Running in FDPClient</p>`

**Comment by liulihaocai** [comment]
ty, maybe u can create a pull request next time
