### ISSUE TITLE
More bypasses

### ISSUE THREAD

**Issue by gabrielvicenteYT** [UnlegitMC/FDPClient#23]
Hi, i want you guys to work on other bypasses.
Example:
Verus Bypasses
Mineplex Bypasses
Cubecraft Bypasses
MinemenClub Bypasses
potion.land Bypasses
pvp.land Bypasses
ETC ETC ETC

**Comment by Dudufccg** [comment]
FDP client is a client that was made for redesky.

**Comment by gabrielvicenteYT** [comment]
Yes, but it would be great if they added more bypasses.

**Comment by liulihaocai** [comment]
i cant bypass these server,i can only bypass redesky
but i'll try it :D

**Comment by liulihaocai** [comment]
jogar.mush.com.br bypass added

**Comment by THEKEMER** [comment]
Hi, I would like to propose to add a Good matrix AntiBot, for example, as in the updated client liquidboune b73, the name of the mod is AlwayslnRadius

**Comment by THEKEMER** [comment]
Hi, I would like to propose to add a Good matrix AntiBot, for example, as in the updated client liquidboune b73, the name of the mod is AlwayslnRadius

**Comment by liulihaocai** [comment]
added ALOT OF bypass :)
