### ISSUE TITLE
FakePlayer module 

### ISSUE THREAD

**Issue by molkecchidapochat** [UnlegitMC/FDPClient#232]
Hello :)
Maybe add new feature/module called "FakePlayer"
FakePlayer module will summons a fake player client-side like real player so player can config their modules (Killaura etc.)
Thank you.

**Comment by xkeksi** [comment]
???????????????????

**Comment by shuhai2008** [comment]
Anticheat test server can do this better
Join IP:
tree.ac
eu.loysia.cn

**Comment by molkecchidapochat** [comment]
> Anticheat test server can do this better
> Join IP:
> tree.ac
> eu.loysia.cn

nice to know, thanks
