### ISSUE TITLE
Error .

### ISSUE THREAD

**Issue by JahamesFan** [UnlegitMC/FDPClient#237]
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
Exit Code: -1 

This is the message i get when i launch fdp. I need help asap

**Comment by ll11l1lIllIl1lll** [comment]
remove mcDataDir/FDPClient-1.8/*

**Comment by liulihaocai** [comment]
your config broken :(
idk why but we are sorry to hear that
