### ISSUE TITLE
I Can't Play v2.0.0pre1

### ISSUE THREAD

**Issue by ThanhMinecraftVN123** [UnlegitMC/FDPClient#244]
This error says: 
"Minecraft did not start due to an unknown error! Probably it happened for your mods, try to delete it or read below You have installed mods. We advise you to assemble your assembly using our mod-pack system link . How it helps! 

1) If the game breaks (crashes) with your mods, then turn off all the mods (click on the green box to the right of the installed mod) and launch the launcher (to make sure that the empty build works ), then activate (click on the gray box) a few pieces or one and start the game, so you will understand at what point the problem arises. 

2) Make backups of your working assemblies. 

3) Send your friends with builds. For a more precise definition, the Use the following guidelines for working with the console: https://tlauncher.org/en/error-start-minecraft.html If all else fails, then write to our group for help via the link https ://vk.com/tlauncher"

**Comment by ydertgf** [comment]
i used normal mc launcher with legacy gui and it worked after 20 seconds

or it was because i clicked the alt manager button

**Comment by liulihaocai** [comment]
maybe fixed

**Comment by liulihaocai** [comment]
> i used normal mc launcher with legacy gui and it worked after 20 seconds
> 
> or it was because i clicked the alt manager button

your pc dont support ultralight, please add JVM argument -Dfdp-legacy-ui to use the legacy ui
