### ISSUE TITLE
Keeps crashing in new version

### ISSUE THREAD

**Issue by SomebodyYouDidntMeet** [UnlegitMC/FDPClient#245]
when I launch the new version it always crashes even with the old gui arguments

**Comment by ydertgf** [comment]
are you using mojang launcher?

**Comment by SomebodyYouDidntMeet** [comment]
no

> are you using mojang launcher?

no im using tlauncher

**Comment by SomebodyYouDidntMeet** [comment]
> are you using mojang launcher?

it used to work with 1.4.0

**Comment by SomebodyYouDidntMeet** [comment]
i tried with mojang launcher still no work

**Comment by liulihaocai** [comment]
duplicated with #244
