### ISSUE TITLE
esp

### ISSUE THREAD

**Issue by ydertgf** [UnlegitMC/FDPClient#248]
esp bugs out on modes jello and shader outline
![2021-09-04_10 32 16](https://user-images.githubusercontent.com/83089186/132099905-ffdcd3d4-d676-4cf0-b57f-d24e43734632.png)
![2021-09-04_10 32 23](https://user-images.githubusercontent.com/83089186/132099908-98eddf93-4e7e-4036-b25f-1a964f49f66b.png)

**Comment by liulihaocai** [comment]
your pc dont support it

**Comment by liulihaocai** [comment]
lb have the same issue so idk how 2 fix
