### ISSUE TITLE
fonts 😱 first issue

### ISSUE THREAD

**Issue by opZywl** [UnlegitMC/FDPClient#250]
the FDP fonts are not so nice, the (MicroRei font) is a little faded, the old fonts were better, I say this because it gets a little ugly and you can hardly see it sometimes and just a suggestion I think it would be cool to use the defaults still

**Comment by opZywl** [comment]
suggest: quicksand font

**Comment by exit-scammed** [comment]
i think https://www.google.com/get/noto/ is also a good multilingual font

**Comment by opZywl** [comment]
yees nice font

**Comment by liulihaocai** [comment]
no its the fontrenderer issue, i'll try hard 2 fix that

**Comment by liulihaocai** [comment]
fixed

**Comment by ShadowIsNotTrash** [comment]
> fixed

not fixed for me
