### ISSUE TITLE
v2.0.0-PRE1 crashing

### ISSUE THREAD

**Issue by brlol** [UnlegitMC/FDPClient#251]
[crash-2021-09-04_11.26.10-client.txt](https://github.com/UnlegitMC/FDPClient/files/7110248/crash-2021-09-04_11.26.10-client.txt)

crash report here

**Comment by ThanhMinecraftVN123** [comment]
paste in the JVM arguments command: -Dfdp-legacy-ui
if it's Tlauncher then paste in JVM arguments and Minecraft arguments but when entering the game there will be no new clickgui and new main menu

**Comment by brlol** [comment]
> paste in the JVM arguments command: -Dfdp-legacy-ui
> if it's Tlauncher then paste in JVM arguments and Minecraft arguments but when entering the game there will be no new clickgui and new main menu

thanks, fixed
