### ISSUE TITLE
V2-0-0 Pre 1 Crash On launch

### ISSUE THREAD

**Issue by TechnoMelon** [UnlegitMC/FDPClient#252]
[crash-2021-09-04_14.28.49-client.txt](https://github.com/UnlegitMC/FDPClient/files/7110324/crash-2021-09-04_14.28.49-client.txt)

**Comment by ThanhMinecraftVN123** [comment]
paste in the JVM arguments command: -Dfdp-legacy-ui
if it's Tlauncher then paste in JVM arguments and Minecraft arguments but when entering the game there will be no new clickgui and new main menu

**Comment by TechnoMelon** [comment]
will i ever get to use the new ui?

**Comment by liulihaocai** [comment]
#244

**Comment by Hop2full** [comment]
> paste in the JVM arguments command: -Dfdp-legacy-ui if it's Tlauncher then paste in JVM arguments and Minecraft arguments but when entering the game there will be no new clickgui and new main menu

how to add
