### ISSUE TITLE
Crashing.

### ISSUE THREAD

**Issue by AlexBartles2012** [UnlegitMC/FDPClient#258]
Hi FDPClient v2.0.0-PRE1 is crashing on the MOJANG screen can you help me please?

**Comment by ll11l1lIllIl1lll** [comment]
logs

**Comment by AlexBartles2012** [comment]
add me on discord AlexB#7653

**Comment by AlexBartles2012** [comment]
[crash-2021-09-05_08.24.15-client.txt](https://github.com/UnlegitMC/FDPClient/files/7111200/crash-2021-09-05_08.24.15-client.txt)

**Comment by AlexBartles2012** [comment]
Also I tried removing all mods except from FDP and Optifine

**Comment by sigmaclientwastaken** [comment]
-noverify should fix

**Comment by FakeMan1331** [comment]
> -noverify should fix

Still crashes for me. I tried removing every single mod except fdp, and it still crashes on mojang screen

**Comment by FakeMan1331** [comment]
nvm solved. Support says to delete all jvm and add -Dfdp-legacy-ui=Rise_best_client_better_than_FDP_Client -Dno-server-block -noverify

**Comment by liulihaocai** [comment]
#244
