### ISSUE TITLE
The new gui of fdp client 2.0.0v1

### ISSUE THREAD

**Issue by DiazNurZ1** [UnlegitMC/FDPClient#270]
i really like the model of it but i dont know why its lagging my computer soo much that it made it crash alot of times now i know you can downgrade but i dont want to cause it looks way more cleaner can you guys please make the gui kinda playable? thanks! i really like the client soo far i have been using it since version 1.3.2!

**Comment by liulihaocai** [comment]
#244 and new ui used html so it will cost more cpu and gpu
