### ISSUE TITLE
gui

### ISSUE THREAD

**Issue by DiazNurZ1** [UnlegitMC/FDPClient#273]
new gui is very laggy whenever i press click gui it lags soo much until 1 fps can the gui be less laggy cause its very hard to make configs with the new 2.0.0 update

**Comment by liulihaocai** [comment]
i'll try hard to make it better

**Comment by DiazNurZ1** [comment]
thank you thank you i really like it :D <3

Pada tanggal Kam, 9 Sep 2021 pukul 05.38 liulihaocai <
***@***.***> menulis:

**Comment by liulihaocai** [comment]
#458
