### ISSUE TITLE
bug: rotations do not respect user movement

### ISSUE THREAD

**Issue by xcfrg** [UnlegitMC/FDPClient#276]
If you try to move while using killaura rotations, your character will move in the direction the actual rotations are (the ones visible in f5) and not which way you are facing on your screen (in first person). 

This makes it very hard to control and can be a especially detrimental in games with lots of void.

**Comment by zWTbz** [comment]
turn off the strafe in killaura

**Comment by liulihaocai** [comment]
.killaura strafe off
