### ISSUE TITLE
crashing on new relese

### ISSUE THREAD

**Issue by KoltieHax** [UnlegitMC/FDPClient#279]
for some reason fdp client keeps crashing on the new 2.0 relese but i can use any other verstion for some reson

**Comment by playingmyvagina** [comment]
same heree..

**Comment by PaulXD123** [comment]
same here

**Comment by Not-LagsAlot** [comment]
deletefdp.today there is an "in-depth" tutorial on how to fix your issue

**Comment by ll11l1lIllIl1lll** [comment]
^

**Comment by liulihaocai** [comment]
#267

**Comment by KoltieHax** [comment]
sorry
