### ISSUE TITLE
No TheAltening Support?

### ISSUE THREAD

**Issue by Nicster205** [UnlegitMC/FDPClient#28]
Original Liquidbounce has TheAltening support, where you can put a token or your id to gen and use alts from there.
FDPClient has no such feature, therefore, I might go back to lint.

**Comment by shuhai2008** [comment]
The altening is obsolete and we won't join it again

**Comment by Infamess** [comment]
> The altening is obsolete and we won't join it again

Not really LMAO

**Comment by shuhai2008** [comment]
> > 变迁已过时，我们不会再加入
> 
> 不是真的LMAO

It's true
