### ISSUE TITLE
KillAura

### ISSUE THREAD

**Issue by TechnoMelon** [UnlegitMC/FDPClient#294]
Whenever I enable it doesn't work in pre 2

**Comment by ll11l1lIllIl1lll** [comment]
There are many possible explanations for this problem. Before you contact us, check if one of the following approaches solves it:
• Make sure players are marked as targets.
• If AntiBot is enabled, disable it for testing.
• Make sure you are not using mods which are known to cause such problems (e.g. BetterAnimations).
• Some servers attempt to confuse KillAuras by pretending players are dead. To ensure that KillAura still attacks, activate Dead as target.
