### ISSUE TITLE
FDP client launch exit with -1

### ISSUE THREAD

**Issue by lantun44** [UnlegitMC/FDPClient#303]
Ive installed the FDP client as it schould(with the forge 1.8.9, put the FDP.jar in mods folder) run the forge, but the launch exits with the variable -1 
here is the game launch crash picture:

![image](https://user-images.githubusercontent.com/90568116/132995302-c1f4ddd5-566d-444f-93b8-87672fafba56.png)

**Comment by liulihaocai** [comment]
#267
