### ISSUE TITLE
How do i use the configs?

### ISSUE THREAD

**Issue by Phrogage** [UnlegitMC/FDPClient#31]

**Comment by ll11l1lIllIl1lll** [comment]
copy config to mcDataDir/FDPClient-1.8/configs
type ".config load <config name>" on chat in game

**Comment by guimc233** [comment]
Put your config file to `McDataDir/FDPClient-1.8/configs`
The file name must be `<configName>.json`
Then using command `.config load <configName>` in game to load config.

_(I can only a little English D: )_
