### ISSUE TITLE
build.gradle

### ISSUE THREAD

**Issue by liulihaocai** [UnlegitMC/FDPClient#313]
this have some issues when upgrade to gradle6, like shadowJar dont expect some files, fomatting issue, Ui resources is not included  
but i'll fix it, i create this issue to make me dont forgot it

**Comment by ENDER1355** [comment]
"This has some issues when upgrading to Gradle6 like ShadowJar, don't except some files, This is a formatting issue, UI Resources are not included, but I'll fix it, I created this issue to make not forgot about it."
