### ISSUE TITLE
Error de pantalla negra

### ISSUE THREAD

**Issue by Focus887** [UnlegitMC/FDPClient#33]
Al ejecutar el cliente se me abre el cliente pero se queda la pantalla de carga en negro y luego me dice que no responde. Otra duda. Cómo se instala el cliente?

**Comment by liulihaocai** [comment]
please speak english or chinese

**Comment by ll11l1lIllIl1lll** [comment]
Excluir .minecraft
Reinicie o minecraft
saia do jogo
Copie FDPClient para a pasta mods

**Comment by shuhai2008** [comment]
Usted debe hacer preguntas en inglés o chino
Primero debe instalar la versión 1.8.9 de Forge para su Minecraft 1.8.9 ("https://files.minecraftforge.net/net/minecraftforge/forge/") Después de acceder a la carpeta «% appdata% /. Minecraft », cree una nueva carpeta mods, coloque el archivo cliente FDP en la carpeta mods, y asegúrese de abrir el juego 1.8.9forge en lugar del cliente puro 1.8.9

**Comment by shuhai2008** [comment]
El tutorial anterior es sólo para el juego con un iniciador oficial. Si utiliza otro iniciador, trate de encontrar el Directorio (.Minecraft) del iniciador e intentar instalar Forge, o puede cambiar el iniciador oficial
