### ISSUE TITLE
AutoArmor was not in Combat List Any Help please

### ISSUE THREAD

**Issue by ScriptingSki** [UnlegitMC/FDPClient#349]
AutoArmor was not in Combat List Any Help please

**Comment by MCCheatDeveloper** [comment]
Someone (@liulihaocai 😕) decided to merge it into inventory cleaner (horrible idea)

**Comment by opZywl** [comment]
> Someone (@liulihaocai 😕) decided to merge it into inventory cleaner (horrible idea)

true AutoArmor module better
