### ISSUE TITLE
Cant use html ui

### ISSUE THREAD

**Issue by technicalgamerop** [UnlegitMC/FDPClient#352]
I like how you cant use html ui and its only for windows 11 and linux try fixing it

**Comment by mccboy520** [comment]
so why not use old UI , new vertion can choose UI' type in the game .

**Comment by Araei98** [comment]
Relley i have windows 11 nad its don't work how

**Comment by sarp3592** [comment]
same issue it crashes for me both

**Comment by liulihaocai** [comment]
#458
