### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by SomebodyYouDidntMeet** [UnlegitMC/FDPClient#353]
whenever I load a config it crashes

**Comment by liulihaocai** [comment]
crash report?

**Comment by SomebodyYouDidntMeet** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-2.0.0.jar)
  TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/21/21 10:18 PM
Description: Updating screen events

java.lang.NoSuchFieldError: settingsDir
	at net.ccbluex.liquidbounce.features.command.commands.LocalAutoSettingsCommand.getLocalSettings(LocalAutoSettingsCommand.kt:139)
	at net.ccbluex.liquidbounce.features.command.commands.LocalAutoSettingsCommand.tabComplete(LocalAutoSettingsCommand.kt:126)
	at net.ccbluex.liquidbounce.features.command.CommandManager.getCompletions(CommandManager.kt:62)
	at net.ccbluex.liquidbounce.features.command.CommandManager.autoComplete(CommandManager.kt:46)
	at net.minecraft.client.gui.GuiChat.handler$keyTyped$zzl000(GuiChat.java:605)
	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:577)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:533)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.features.command.commands.LocalAutoSettingsCommand.getLocalSettings(LocalAutoSettingsCommand.kt:139)
	at net.ccbluex.liquidbounce.features.command.commands.LocalAutoSettingsCommand.tabComplete(LocalAutoSettingsCommand.kt:126)
	at net.ccbluex.liquidbounce.features.command.CommandManager.getCompletions(CommandManager.kt:62)
	at net.ccbluex.liquidbounce.features.command.CommandManager.autoComplete(CommandManager.kt:46)
	at net.minecraft.client.gui.GuiChat.handler$keyTyped$zzl000(GuiChat.java:605)
	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:577)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:533)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiChatOF

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['wewaesd'/290, l='MpServer', x=1084.70, y=64.00, z=118.19]]
	Chunk stats: MultiplayerChunkCache: 167, 167
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 220.00,64.00,252.00 - World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 120396 game time, 120396 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityCreeper['Creeper'/2580, l='MpServer', x=1160.50, y=13.00, z=69.50], EntityCreeper['Creeper'/2582, l='MpServer', x=1161.50, y=13.00, z=68.50], EntityPlayerSP['wewaesd'/290, l='MpServer', x=1084.70, y=64.00, z=118.19], EntityCreeper['Creeper'/2624, l='MpServer', x=1029.50, y=22.00, z=180.50], EntityPig['Pig'/2626, l='MpServer', x=1008.94, y=66.00, z=179.44], EntityItem['item.item.seeds'/2627, l='MpServer', x=1110.84, y=64.00, z=110.38], EntityZombie['Zombie'/2138, l='MpServer', x=1052.50, y=30.00, z=141.50], EntitySkeleton['Skeleton'/2153, l='MpServer', x=1021.03, y=21.00, z=147.69], EntityBat['Bat'/2154, l='MpServer', x=1008.41, y=25.59, z=144.94], EntityBat['Bat'/2163, l='MpServer', x=1006.94, y=25.22, z=157.34], EntitySkeleton['Skeleton'/2945, l='MpServer', x=1052.50, y=52.00, z=194.50], EntitySkeleton['Skeleton'/2946, l='MpServer', x=1051.50, y=52.00, z=195.50], EntityPig['Pig'/394, l='MpServer', x=1004.78, y=92.00, z=122.66], EntityItem['item.tile.rail'/2196, l='MpServer', x=1056.88, y=27.00, z=156.22], EntityEnderman['Enderman'/406, l='MpServer', x=1000.56, y=70.00, z=35.86], EntitySheep['Sheep'/407, l='MpServer', x=1005.97, y=71.00, z=42.91], EntitySheep['Sheep'/408, l='MpServer', x=1023.13, y=71.00, z=43.75], EntityItem['item.tile.torch'/2200, l='MpServer', x=1068.84, y=31.00, z=173.66], EntityItem['item.tile.torch'/2201, l='MpServer', x=1061.81, y=33.00, z=160.88], EntityMinecartChest['container.minecart'/410, l='MpServer', x=1023.50, y=29.06, z=63.50], EntitySheep['Sheep'/412, l='MpServer', x=1013.25, y=71.00, z=48.34], EntitySheep['Sheep'/413, l='MpServer', x=1025.06, y=70.00, z=61.97], EntityItem['item.tile.rail'/414, l='MpServer', x=1022.88, y=26.00, z=79.63], EntityItem['item.tile.rail'/415, l='MpServer', x=1022.88, y=26.00, z=78.19], EntityCreeper['Creeper'/416, l='MpServer', x=1017.94, y=22.00, z=64.66], EntityItem['item.tile.rail'/417, l='MpServer', x=1020.59, y=26.00, z=86.88], EntityItem['item.tile.rail'/418, l='MpServer', x=1022.88, y=26.00, z=83.22], EntityItem['item.tile.torch'/419, l='MpServer', x=1021.31, y=29.00, z=107.44], EntityItem['item.tile.torch'/420, l='MpServer', x=1021.16, y=29.00, z=102.56], EntityMinecartChest['container.minecart'/421, l='MpServer', x=1013.50, y=23.06, z=134.50], EntityPig['Pig'/2215, l='MpServer', x=1108.50, y=65.00, z=69.50], EntityPig['Pig'/2216, l='MpServer', x=1110.50, y=65.00, z=69.50], EntityPig['Pig'/2217, l='MpServer', x=1105.16, y=65.00, z=69.44], EntityPig['Pig'/2218, l='MpServer', x=1104.63, y=65.00, z=70.88], EntityZombie['Zombie'/427, l='MpServer', x=1036.50, y=30.00, z=52.50], EntityBat['Bat'/2219, l='MpServer', x=1117.75, y=43.08, z=153.42], EntitySheep['Sheep'/2220, l='MpServer', x=1099.31, y=74.00, z=151.41], EntitySheep['Sheep'/2221, l='MpServer', x=1095.63, y=71.00, z=148.88], EntitySheep['Sheep'/430, l='MpServer', x=1021.88, y=70.00, z=55.41], EntitySheep['Sheep'/2222, l='MpServer', x=1092.50, y=71.00, z=151.50], EntityItem['item.tile.rail'/431, l='MpServer', x=1038.03, y=31.00, z=92.63], EntitySheep['Sheep'/2223, l='MpServer', x=1092.28, y=68.00, z=137.16], EntityItem['item.tile.rail'/432, l='MpServer', x=1039.88, y=31.00, z=93.78], EntityItem['item.tile.torch'/433, l='MpServer', x=1033.22, y=27.00, z=106.50], EntityItem['item.tile.torch'/434, l='MpServer', x=1024.09, y=30.00, z=96.88], EntityItem['item.tile.rail'/435, l='MpServer', x=1037.13, y=31.00, z=99.88], EntityItem['item.tile.torch'/437, l='MpServer', x=1025.25, y=23.00, z=128.94], EntityItem['item.tile.torch'/441, l='MpServer', x=1051.41, y=23.00, z=59.47], EntityItem['item.tile.torch'/442, l='MpServer', x=1043.88, y=30.00, z=64.94], EntityItem['item.tile.torch'/443, l='MpServer', x=1052.22, y=27.00, z=94.81], EntityMinecartChest['container.minecart'/444, l='MpServer', x=1046.50, y=26.06, z=102.50], EntitySheep['Sheep'/445, l='MpServer', x=1053.50, y=72.00, z=110.50], EntityItem['item.tile.rail'/446, l='MpServer', x=1053.13, y=30.00, z=124.13], EntitySheep['Sheep'/447, l='MpServer', x=1053.06, y=75.00, z=111.75], EntitySheep['Sheep'/448, l='MpServer', x=1051.44, y=78.00, z=113.53], EntitySheep['Sheep'/449, l='MpServer', x=1053.91, y=75.00, z=113.25], EntityItem['item.tile.rail'/458, l='MpServer', x=1061.22, y=22.00, z=58.13], EntityItem['item.tile.rail'/459, l='MpServer', x=1061.22, y=22.00, z=60.41], EntityItem['item.tile.rail'/460, l='MpServer', x=1062.72, y=22.00, z=59.66], EntitySkeleton['Skeleton'/461, l='MpServer', x=1068.50, y=29.00, z=86.50], EntityItem['item.tile.torch'/462, l='MpServer', x=1064.16, y=29.00, z=83.88], EntitySkeleton['Skeleton'/463, l='MpServer', x=1064.50, y=29.00, z=86.50], EntityZombie['Zombie'/2255, l='MpServer', x=1034.50, y=19.00, z=169.50], EntityZombie['Zombie'/2256, l='MpServer', x=1022.06, y=29.00, z=162.59], EntityPig['Pig'/2257, l='MpServer', x=1009.44, y=66.00, z=171.13], EntitySheep['Sheep'/2258, l='MpServer', x=1010.88, y=66.00, z=172.78], EntityMinecartChest['container.minecart'/467, l='MpServer', x=1068.50, y=29.06, z=106.50], EntityItem['item.tile.torch'/468, l='MpServer', x=1062.63, y=29.00, z=99.88], EntityMinecartChest['container.minecart'/469, l='MpServer', x=1071.50, y=26.06, z=120.50], EntityItem['item.tile.torch'/470, l='MpServer', x=1070.91, y=25.00, z=131.69], EntityItem['item.tile.torch'/471, l='MpServer', x=1061.09, y=31.00, z=128.88], EntityBat['Bat'/474, l='MpServer', x=1081.63, y=25.00, z=40.50], EntityZombie['Zombie'/478, l='MpServer', x=1076.50, y=47.00, z=61.50], EntityItem['item.tile.rail'/479, l='MpServer', x=1073.88, y=34.00, z=61.97], EntityItem['item.tile.rail'/480, l='MpServer', x=1073.56, y=34.00, z=62.72], EntityCreeper['Creeper'/481, l='MpServer', x=1084.50, y=47.00, z=65.50], EntityItem['item.tile.rail'/482, l='MpServer', x=1074.88, y=34.00, z=65.75], EntityItem['item.tile.rail'/484, l='MpServer', x=1072.13, y=34.00, z=75.19], EntityItem['item.tile.rail'/485, l='MpServer', x=1073.69, y=34.00, z=76.25], EntityItem['item.tile.torch'/486, l='MpServer', x=1083.88, y=34.00, z=72.25], EntityItem['item.tile.torch'/487, l='MpServer', x=1073.13, y=34.00, z=76.25], EntitySheep['Sheep'/2279, l='MpServer', x=1007.44, y=67.00, z=175.28], EntityItem['item.tile.torch'/488, l='MpServer', x=1073.69, y=30.00, z=84.88], EntitySkeleton['Skeleton'/2280, l='MpServer', x=1005.50, y=62.00, z=185.50], EntityItem['item.tile.torch'/489, l='MpServer', x=1083.59, y=30.00, z=80.19], EntityPig['Pig'/2281, l='MpServer', x=1007.72, y=66.00, z=178.63], EntityItem['item.tile.torch'/490, l='MpServer', x=1073.13, y=23.00, z=120.88], EntitySheep['Sheep'/2282, l='MpServer', x=1007.81, y=76.00, z=177.50], EntitySheep['Sheep'/2283, l='MpServer', x=1093.88, y=89.00, z=165.88], EntitySheep['Sheep'/2284, l='MpServer', x=1092.16, y=89.00, z=164.16], EntitySpider['Spider'/493, l='MpServer', x=1098.50, y=68.00, z=44.50], EntitySheep['Sheep'/2285, l='MpServer', x=1090.81, y=90.00, z=167.84], EntitySheep['Sheep'/2286, l='MpServer', x=1094.50, y=89.00, z=167.50], EntitySkeleton['Skeleton'/2287, l='MpServer', x=1059.50, y=23.00, z=124.50], EntityCreeper['Creeper'/495, l='MpServer', x=1089.50, y=68.00, z=62.50], EntitySpider['Spider'/496, l='MpServer', x=1088.38, y=68.00, z=50.81], EntityBat['Bat'/497, l='MpServer', x=1103.50, y=50.06, z=70.88], EntityBat['Bat'/498, l='MpServer', x=1080.19, y=49.03, z=66.25], EntityCreeper['Creeper'/499, l='MpServer', x=1089.50, y=68.00, z=65.50], EntityCreeper['Creeper'/501, l='MpServer', x=1100.34, y=68.22, z=143.69], EntityItem['item.item.seeds'/3317, l='MpServer', x=1146.66, y=64.00, z=149.28], EntityItem['item.item.rottenFlesh'/3321, l='MpServer', x=1101.36, y=64.00, z=120.82]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1310515480 bytes (1249 MB) / 1946157056 bytes (1856 MB) up to 10603200512 bytes (10112 MB)
	JVM Flags: 9 total; -Xmn128M -Xmx10088M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_M5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAAAA	tlauncher_custom_cape_skin{1.4} [TLSkinCape] (tlskincape_1.8.9-1.4.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-2.0.0.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	Launched Version: ForgeOptiFine 1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !     §4Offensive §cHearts §8[§fV§72§8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by SomebodyYouDidntMeet** [comment]
uhh hello?
