### ISSUE TITLE
[Killaura & InfiniteAura] 

### ISSUE THREAD

**Issue by opZywl** [UnlegitMC/FDPClient#356]
I noticed that the Killaura and InfiniteAura are not working noswing, and only visually but for people who are hitting this was pretty cool and could be fixed

other suggestion from killaura and others: remove as killaura Marks and create a "KillESP" module and make all tagged seen when entering combat
even if using autoclick or infinite aura whenever the connected module would show the marks

InfiniteAura: Timer speed option

**Comment by mccboy520** [comment]
from our client's first vertion , killaura is broken ( still) . in the future , it will be fixed , i will let liuli build next vertion with fixing in days .
