### ISSUE TITLE
REQUESTS: / Some things that have been removed

### ISSUE THREAD

**Issue by opZywl** [UnlegitMC/FDPClient#357]
change name InventoryCleaner to InvCleaner
change name InventoryMove to InvMove
readd AutoArmor Module
readd my pull request (TargetInfo - PlayerInfo) #336 
readd VCLIP/HCLIP
add AirJump Module

**Comment by MCCheatDeveloper** [comment]
Commit 7be9cce also broke font rendering, it looks much worse now.

**Comment by MCCheatDeveloper** [comment]
I'll submit a PR that reverts part of 700e77b (the autoarmor part, there were some other changes that are fine)

**Comment by MCCheatDeveloper** [comment]
Values in the clickgui are also completely broken...

**Comment by mccboy520** [comment]
we are sorry for these questions . you can get old source code and build .
