### ISSUE TITLE
plz tell how to istall it

### ISSUE THREAD

**Issue by opsubhro27** [UnlegitMC/FDPClient#366]
i have downloaded the java kinda file now tell me how to install it

**Comment by liulihaocai** [comment]
use google

**Comment by opsubhro27** [comment]
bruh i used google and found nothing tell me where i can get it 
OR
all the steps 
and what type of behavior is this like ""use google""
u r supposed to assist me

**Comment by ll11l1lIllIl1lll** [comment]
**ggrks**
