### ISSUE TITLE
smooth rotations

### ISSUE THREAD

**Issue by 6alpha9** [UnlegitMC/FDPClient#389]
After last update the smooth rotations in killaura was added which could be used to bypass matrix checks but unfortunately its been done poorly and flags even more than custom rotations, but theres another problem.
If you have "custom" rotations and randomcenter (which is mandatory to bypass matrix) enabled with turnspeed higher than 20 you will flag for "shake component" because turnspeed also affect the patern (its stupid). Keeping the turnspeed value below 20 will make killaura very slow an irresponsible.
So Im asking devs if they could make random center values. This would help to bypass more anticheats.

**Comment by ll11l1lIllIl1lll** [comment]
Your brain issues

**Comment by ll11l1lIllIl1lll** [comment]
I set TurnSpeed to 40-80 and I got 0.00000000000% flag (test.matrix.rip with 357ms ping)

**Comment by 6alpha9** [comment]
random center on or off?

**Comment by ll11l1lIllIl1lll** [comment]
Cubic

**Comment by 6alpha9** [comment]
But the states for random center are true or false. Im a bit confused rn

**Comment by 6alpha9** [comment]
https://www.youtube.com/watch?v=amxl8s-hDKQ
Here is what I mean

**Comment by MCCheatDeveloper** [comment]
> 
> 
> But the states for random center are true or false. Im a bit confused rn

Use the latest github actions build, you can now select different modes for random center

**Comment by contionability** [comment]
you can simple turn off slientrotation then you can see how it works

**Comment by 6alpha9** [comment]
Just downloaded it and it works perfrectly. TYSM
