### ISSUE TITLE
 Problems with the ftp client with crashes.

### ISSUE THREAD

**Issue by FivePlugins** [UnlegitMC/FDPClient#40]
Hello, I am an FDP client user, but when I do some commands/things on the client it just crashes, example: I give the command .localsetting load <My Config> and nothing happens after a few seconds the client crashes.

**Comment by guimc233** [comment]
Can you upload the client log to help us analyze the problem?

**Comment by liulihaocai** [comment]
if you dont using the latest version, try use latest version
if you are on the latest version, describe what you did so make us able to reproduct the crash

**Comment by liulihaocai** [comment]
timed out....
