### ISSUE TITLE
Buggy values positions in every module (2.0 version)

### ISSUE THREAD

**Issue by khecn** [UnlegitMC/FDPClient#403]
![_lLhf6tEopc](https://user-images.githubusercontent.com/91737125/135625158-c11bacd2-e4c1-4361-b963-fecd708b52bc.jpg)

**Comment by liulihaocai** [comment]
fontrenderer issue

**Comment by SailentWasTaken** [comment]
So when will it be fixed? The modul3s look like a mess cuz of it
