### ISSUE TITLE
ggggg

### ISSUE THREAD

**Issue by RangelMK** [UnlegitMC/FDPClient#43]
pls don’t remove SwitchChangeAtkTimes #returns pls add MultiNCP and NCP rotations and mark custom fdpclient yyyyyy @opZywl @liulihaocai

**Comment by opZywl** [comment]
> pls don’t remove SwitchChangeAtkTimes #returns pls add MultiNCP and NCP rotations and mark custom fdpclient yyyyyy @opZywl @liulihaocai

did n remove it
I was just trying to add another code, I think after liulihaocai sees it will add it again or maybe conflict with the new code 
😶‍🌫️
