### ISSUE TITLE
Html Renderer

### ISSUE THREAD

**Issue by liulihaocai** [UnlegitMC/FDPClient#458]
use a custom version of https://github.com/montoyo/mcef to support more html/js/css features and fix crashing and fps dropping problem

**Comment by LeonThePubertier** [comment]
can u send me the custom version, cause the one i downloaded from them is only for 1.8 not for 1.8.9 and fdp runs in 1.8.9 so ye....

**Comment by Rutra09** [comment]
![obraz](https://user-images.githubusercontent.com/46402302/143398164-47f5df26-c8a5-4a76-9839-670fa86d9703.png)

**Comment by Pepeshki** [comment]
> ![obraz](https://user-images.githubusercontent.com/46402302/143398164-47f5df26-c8a5-4a76-9839-670fa86d9703.png)

This
