### ISSUE TITLE
Spartan b372 Disabler

### ISSUE THREAD

**Issue by contionability** [UnlegitMC/FDPClient#462]
FakeLag delay 100 duration 400 (With C0F and C00)
Delay C0F for 570 ms
Delay C00 for 480 ms (这俩单独进行delay，相当于重复发 C0F C00)
Ex: Input: C0F C03 C00
Delay 400ms -> Send C0F C03 C00
Delay 480ms -> Send C00 (TimeSchedule)
Delay 570ms -> Send C0F (TimeSchedule)
Output: 400ms C0F C03 C00 480ms C00 570ms C0F
(我相信你能写出来的 @liulihaocai

**Comment by FengXiaoSkidGod** [comment]
@liulihaocai 是不是忘了 :)

**Comment by ll11l1lIllIl1lll** [comment]
@liulihaocai 是不是忘了 :)
