### ISSUE TITLE
BUGS/REPORTS/SUGGESTIONS/REQUESTS FROM GUYS DISCORD

### ISSUE THREAD

**Issue by opZywl** [UnlegitMC/FDPClient#490]
Suggestions from discord I separated the best and most relevant I saw

1) Search option HTML

![image](https://user-images.githubusercontent.com/86253343/137607329-e5621b83-a49e-4b1c-b7da-4182a60d7c0f.png)

2) Repair MLG mode in NoFall (Doesn't work) - BUG
3) Cosmetics (Wings, hat's, bandanas, shield and other) - REQUEST 
4) Item physics Module -  (VERY REQUEST FROM GUYS)
5) .tp command (liuli never cared about this command -_-) - REQUEST
6) Fancy notifications - Request
7) MurderMustery Murderer finder - request
8) Better Scaffold mark & block counter - Request
9) people ask a lot of "TargetStrafe" I don't think it's that useful but it's one of the modules I see most asked for.
10) leave all killaura marks in a single "KilllESP" module and it is possible for all combat modules to show the mark when it is on. - my request
11) fix KillAura/InfiniteAura  NoSwing (it's not working just visual):/ - bug
12) stop killaura from targeting yourself, this occurs when in blink and is super annoying - BUG
13) add PlayerInfo (REQUEST)

**Comment by 6alpha9** [comment]
12. can be fixed
antibot - always in radius or swing
