### ISSUE TITLE
[Detection] Longjump modes BlocksMC and BlocksMC 2 no longer work + how to fix.

### ISSUE THREAD

**Issue by Hazsi** [UnlegitMC/FDPClient#603]
The BlocksMC and the BlocksMC2 longjump modes are made for the older AAC version of BlocksMC, as opposed to the newer Verus version. If I'm wrong, they still kick almost every time regardless. 

I believe this is due to the timer, which from my testing, the Verus on BlocksMC is really sensitive to. 

The NCP longjump works perfectly, even with a boost value of 10 (the maximum). The old BlocksMC longjumps should be replaced with the NCP mode with a boost value of 10.

In my testing, this has never kicked during normal use, as long as I don't spam it, or jump backwards/sideways. This kicks **far** less than the current implementation and is significantly longer/faster. From my testing, the NCP boost value doesn't affect the kick rate. It's worth noting that I'm using the OldVerusCombat disabler for all of these tests.

**Comment by Onkar-1** [comment]
use oldverusmove disabler for movement disabler

**Comment by contionability** [comment]
why not use fly
