### ISSUE TITLE
FDP client crashing

### ISSUE THREAD

**Issue by n7awl** [UnlegitMC/FDPClient#606]
SO when i try to open fdp 2.0.0, it opens just fine, but when I click either Legacy  ui or html ui it crashes. I tried several ways to fix this but couldn't.
![Screenshot 2021-10-31 143809](https://user-images.githubusercontent.com/93473796/139581269-a509fc04-8c59-4ee0-b489-12b4ea2afee5.png)
I am on windows 10, but please if you can give me a solution for this

**Comment by contionability** [comment]
try to delete FDPClient-1.8 and try again
