### ISSUE TITLE
my pc dosent support the new ui and idk how to change it

### ISSUE THREAD

**Issue by FoxyYTT** [UnlegitMC/FDPClient#607]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by zezayne** [comment]
put -Dfdp-legacy-ui in jvm arguements

**Comment by llama-for3ver** [comment]
> put -Dfdp-legacy-ui in jvm arguements

Only works in 2.0.0-PRE1
doesnt do anything in recent versons
