### ISSUE TITLE
[Bug] screen goes black when turning on blur in huddesigner

### ISSUE THREAD

**Issue by Minecon724** [UnlegitMC/FDPClient#608]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
title /\

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to huddesigner
2. Click on any element
3. Scroll down to 'blur' and turn it on

**Expected behavior**
it working?

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
https://streamable.com/c2ibaj

**System Information**
 - OS: [e.g. Windows 10] Windows 10
 - Minecraft Version: [e.g. 1.8.9] 1.8.9
 - Forge Version: [e.g. 11.15.1.2318] 11.15.1.2318
 - FDPClient Version: [e.g. 2.0-PRE2] 2.0.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- optifine m6_pre1
- viabackwards

**Comment by exit-scammed** [comment]
check if you have alr turned on fast render in optifine settings, if yes then turn it off.

**Comment by Minecon724** [comment]
it works ty
