### ISSUE TITLE
SwitchDelay and BlockRange settings for killaura

### ISSUE THREAD

**Issue by sduoduo233** [UnlegitMC/FDPClient#61]
add switch delay and blockrange settings for killaura

**Comment by sduoduo233** [comment]
thanks

**Comment by contionability** [comment]
I'll add it when I'm free
maybe 14days later :(
(liuli is stucking on his new client)

**Comment by opZywl** [comment]
hey i have a new clickgui and you might like it, is there any way to send it to you?

**Comment by FengXiaoSkidGod** [comment]
future 
We will build 1.12.2 FDPClient

**Comment by opZywl** [comment]
> future 
> 
> We will build 1.12.2 FDPClient

i uploaded a new clickgui, if you can look at my source i added :0 if you can check

**Comment by FengXiaoSkidGod** [comment]
ok

**Comment by RangelMK** [comment]
please, news clickgui styles https://github.com/lukflug/PanelStudio and add Esp Skeleton, esp player item,
new killaura with switchdelay and blockrange and priority armor breaker for HVH
command .tp (teleport) command
add FullBright AirJump BlockWalk and autoblock modes for Killaura and timer option dependencies in Infinity aura and also do not teleport option and arraylist with space option in module, add NoRender AutoSword
PointerESP and KillESP and CapeCustom & watermaker and icons notifications add a namespoof .nick spoof and show skin and add more shades of colors for example dark in arraylist

**Comment by FengXiaoSkidGod** [comment]
Has been received, may not be updated at this time, because we are preparing for the 1.12 project

**Comment by RangelMK** [comment]
pls don't let 1.8.9 die enter the fdpclient discord server and you will see many people every day asking for suggestions I sent the most requested ones here

**Comment by FengXiaoSkidGod** [comment]
Ok i will pay attention

**Comment by RangelMK** [comment]
please add new stuff like eg Killaura Switchdelay, blockrange, autoblock, update Infinity aura for 200 reach and criticals and 20 cps 
add Radar, add AntiFireBall add Norender add new clickgui with icons like astolfo

**Comment by opZywl** [comment]
> I'll add it when I'm free
> maybe 14days later :(
> (liuli is stucking on his new client)

yoo check my pull requests I have that (SwitchDelay and BlockRange and Armor Priority)

**Comment by RangelMK** [comment]
now only switchdelay from 1 to 1000 and armor priority are missing

**Comment by liulihaocai** [comment]
this already added
