### ISSUE TITLE
How to fix the vertex font renderer glitch

### ISSUE THREAD

**Issue by ShadowIsNotTrash** [UnlegitMC/FDPClient#618]
**To FIX it**
Steps to fix it:
1. Go to 'fdp folder'
2. open 'Special.json'
3. set the "use-glyph-fontrenderer" 'to true'
4. launch the game and it will be fixed

**Comment by SpaceBurn** [comment]
I don't see that option in my special json file

**Comment by scorchhy** [comment]
oh my god you genius, thank you so much

**Comment by Rutra09** [comment]
Don't work to me
Were specify i must put these argument?
![obraz](https://user-images.githubusercontent.com/46402302/143397822-ac9cc190-2d70-43a9-b6b3-c775fd45b5f4.png)

**Comment by llama-for3ver** [comment]
> I don't see that option in my special json file

same

**Comment by llama-for3ver** [comment]
if it isn't there then put it in

**Comment by Mitsobabis** [comment]
> **To FIX it** Steps to fix it:
> 
> 1. Go to 'fdp folder'
> 2. open 'Special.json'
> 3. set the "use-glyph-fontrenderer" 'to true'
> 4. launch the game and it will be fixed

Thank u very much!!
