### ISSUE TITLE
[Bug] <FDP 2.0.1> 

### ISSUE THREAD

**Issue by Sqrinz** [UnlegitMC/FDPClient#620]
Keep Crashing when i selected the new ui or the normal ui, it says this file is not JSON
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to Minecraft Launcher/ Tlauncher
2. Click on Forge
3. When i launched and i selected the old ui and crash

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by zWTbz** [comment]
where the log
