### ISSUE TITLE
Broken spoof autoblock in scaffold settings

### ISSUE THREAD

**Issue by Arcadius159** [UnlegitMC/FDPClient#624]
My matrix scaffold was working perfectly on spoof mode but after latest beta its broken and it doesnt work and flags for Type I which is autoblock spoof according to this :
https://forums.ccbluex.net/topic/1654/breaking-down-matrix-s-scaffold-checks?_=1636383741138

**Comment by contionability** [comment]
but scaffold didn't change at all
maybe they updated their anticheat

**Comment by Arcadius159** [comment]
I tested both versions on matrix 6.5.0 on loyisa and it still flags but the older build doesnt

**Comment by contionability** [comment]
try the latest build
