### ISSUE TITLE
[Bug] I cant load the client in any way

### ISSUE THREAD

**Issue by S0lvee** [UnlegitMC/FDPClient#628]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When i just launch FDP, and just want to access it, it just crashes pls fix.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to Minecraft launcher
2. Click on Play
3. Click on either HTML or Legacy UI
4. Minecraft crashes

**Expected behavior**
Just load the client

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
an unexpected error has occurred and the game has crashed minecraft exit code 0

```text
[Paste Here]
```

**System Information**
 - OS: Windows 10 home
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 2.01

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- I have not

**Additional info**
I just updated my graphics card, so that isnt it

**Comment by zWTbz** [comment]
where the log?

**Comment by LoserFox** [comment]
Htmlui usually does not work well on every computer, and some computers will crash. This is not our problem, but an ultralight problem.
Sorry, your computer cannot run htmlui, please use another mode
