### ISSUE TITLE
[Bug] replaymod compatibility?

### ISSUE THREAD

**Issue by Minecon724** [UnlegitMC/FDPClient#629]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
crashing with replaymod

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. launch fdp with replaymod

**Expected behavior**
it working?

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
https://pastebin.com/DUpcfpeS

**System Information**
 - OS: [e.g. Windows 10] windows 11
 - Minecraft Version: [e.g. 1.8.9] 1.8.9
 - Forge Version: [e.g. 11.15.1.2318] 11.15.1.2318
 - FDPClient Version: [e.g. 2.0-PRE2] 2.0.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- optifine
- replaymod

**Additional info**

**Comment by contionability** [comment]
it works well with replay mod on my pc
