### ISSUE TITLE
[html ui crashing] <my html ui keeps crashing>

### ISSUE THREAD

**Issue by LeonThePubertier** [UnlegitMC/FDPClient#631]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
i don't know, if this is normal and im just stupid but whenever i click on html ui when launching fdp client, it just instantly crashes my game. crash report below

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
i just launched fdp client and clicked on html ui instead of lagacy ui

**Expected behavior**
i thought, it would work and from what i saw in videos, it actually looks really good

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
https://streamable.com/ovkcrz

**Crash Report**
If your game crashed, please paste your crash report below.
https://anonfiles.com/X4Hcy5V1u3/crash-2021-11-16_13.54.32-client_txt

```text
[Paste Here]
```

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9 with fdp client beta
 - Forge Version: idk it just shows up as forge 1.8.9 for me
 - FDPClient Version: beta - name of the jar file: "FDPClient-6f09dc720b8d20db5ca5f4754f01dba5c70aaa50.jar"

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- OptiFine_1.8.9_HD_U_L5.jar

**Additional info**
i hope that you can fix this or contact me if you have a new discord or how to fix it

**Comment by LoserFox** [comment]
Htmlui usually does not work well on every computer, and some computers will crash. This is not our problem, but an ultralight problem.
Sorry, your computer cannot run htmlui, please use another mode
