### ISSUE TITLE
[Bug] <Title Here>

### ISSUE THREAD

**Issue by Zarf-Marf** [UnlegitMC/FDPClient#636]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
My client crashed with exit code 1 after I enable htmlui

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
-optifine

**Comment by LoserFox** [comment]
Htmlui usually does not work well on every computer, and some computers will crash. This is not our problem, but an ultralight problem.
Sorry, your computer cannot run htmlui, please use another mode
