### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZyroxP** [UnlegitMC/FDPClient#638]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
I want to login to html ui but game crashes every time

```text
[Paste Here]
```

**System Information**
 - OS: Windows 10 x64 21H1
 - Minecraft Version: Forge 1.8.9(Tlauncher)
 - Forge Version: .
 - FDPClient Version: 2.0.1
**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by zWTbz** [comment]
Bruh

**Comment by llama-for3ver** [comment]
why
