### ISSUE TITLE
[Bug] new AntiBot and scaffold

### ISSUE THREAD

**Issue by Arcadius159** [UnlegitMC/FDPClient#639]
1. AntiBot - SpawnInCombat is pretty bad because when you are fighting anyone who enters yours or servers render distance is marked as BOT. As fix I suggest adding a range where entity spawn.
2. Scaffold - this bug is pretty old. This is the main reason im using old beta. Firstly the autoblock spoof is bugged and doesnt bypass matrix ( it flags for scaffold type I, which means failed autoblock spoof) This one is fixable by using the switch mode for autoblock, but for some odd reason when I load config from old beta to new beta scaffold flags on jartex and pika even though on old beta it works perfectly.

**Comment by Arcadius159** [comment]
I found another bug in scaffold and that is It has bugged rotations which was fixed in the past but for some reason its here again.

**Comment by contionability** [comment]
try the latest build as I trying to fix it without a PC (bruh)
