### ISSUE TITLE
[Bug] Broken Look

### ISSUE THREAD

**Issue by Rutra09** [UnlegitMC/FDPClient#640]
**Describe the bug**
Gui i client look is broken, it is impossible to use it.

**To Reproduce**
1. Go to Random Server
2. Open Click Gui
3. See client's broken look.

**Expected behavior**
I expect you to help me fix the client's look.

**Screenshots/Video**
![obraz](https://user-images.githubusercontent.com/46402302/143258065-2e77be4b-5e97-447f-80e4-5133140ff939.png)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 2.0.1

**Comment by Rutra09** [comment]
On release v2.0.0-PRE1, running normaly.

**Comment by suckma420** [comment]
#618
