### ISSUE TITLE
[Bug] bootload crash

### ISSUE THREAD

**Issue by martypower2064** [UnlegitMC/FDPClient#649]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
when i load up the game and chose one of the options it crashes

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. load minecraft on a 1.8.9 forge instance with only fdp client as a mod
2. load up game
3. crash

**Expected behavior**
it should not crash

**Screenshots/Video**
log : https://paste.ee/p/okQI8

**Crash Report**
https://paste.ee/p/okQI8

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version:  1.8.9
 - Forge Version:  11.15.1.2318
 - FDPClient Version: 2.0.0

**Other Installed Mods**
none

**Additional info**
i have jre 1.8 running

**Comment by guimc233** [comment]
pls check your network connect or don't use html ui

**Comment by Somethingidk123** [comment]
I want to use html UI as it is cleaner.How do i use?

**Comment by Siddhantisback** [comment]
Skid client 69420. Shameless kids

**Comment by suckma420** [comment]
@Siddhantisback yes yes 
https://www.youtube.com/watch?v=gADqWAdtGxM
https://www.youtube.com/watch?v=48SI0s9VOEU
https://www.youtube.com/watch?v=Ah0WxfDuNNE
