### ISSUE TITLE
[Bug] where is .panic nonrender

### ISSUE THREAD

**Issue by GituserBTW** [UnlegitMC/FDPClient#650]
How do I use .panic nonrender, any alternatives ? Oh btw its not a bug

**Comment by zezayne** [comment]
They probably removed it like how .autosettings wasn't an opnion now on FDP client and you have to find the config itself. if i remembered correctly .panic nonrender does some weird stuff to your config.

**Comment by ll11l1lIllIl1lll** [comment]
pull request pls

**Comment by FartCheese** [comment]
use sigma
