### ISSUE TITLE
Matrix-JartexNetwork Disabler??????

### ISSUE THREAD

**Issue by THEKEMER** [UnlegitMC/FDPClient#653]
Hello, can you make a Disabler like this?
https://www.youtube.com/watch?v=AMxlkS-VX-4&ab_channel=Fals3R

**Comment by cupiditys** [comment]
all it does is spam use packets lol
big servers patched it like an hour after release

**Comment by THEKEMER** [comment]
> все, что он делает, это пакеты использования спама, лол большие серверы пропатчили его через час после выпуска

Hmmmm ok

**Comment by contionability** [comment]
But I still seeing some people can fly in Jartex lmao
