### ISSUE TITLE
[Bug] Rendering of non minecraft elements gose brrrrrrr

### ISSUE THREAD

**Issue by oceaann** [UnlegitMC/FDPClient#654]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
![image](https://user-images.githubusercontent.com/47253870/144320896-04cec71a-fcc7-474c-842d-f107cd2de02b.png)

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Start forge with FDP in mods
2. Select Legacy UI

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: [e.g. 11.15.1.1855]
 - FDPClient Version: 2.0

**Other Installed Mods**
- Optifine

**Comment by guimc233** [comment]
pls use newest version
[Click here](https://getfdp.today/beta.html)

**Comment by oceaann** [comment]
Font still broken 
![image](https://user-images.githubusercontent.com/47253870/144708695-396adbc6-062a-4b3d-8129-8b61139bfe88.png)

**Comment by oceaann** [comment]
And this is legacy ui

**Comment by oceaann** [comment]
@guimc233

**Comment by zWTbz** [comment]
try this https://github.com/UnlegitMC/FDPClient/issues/618#issue-1044980684
