### ISSUE TITLE
[Bug] weird visual bug

### ISSUE THREAD

**Issue by remmy0** [UnlegitMC/FDPClient#663]
**Describe the bug**
a weird visual bug using classic ui

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
idk

**Expected behavior**
a normal screen

**Screenshots/Video**
![2021-12-05_14 13 07](https://user-images.githubusercontent.com/90877171/144731970-d4fbf616-9499-4a55-b4e0-d052cd74c5e7.png)

**Crash Report**
n/a

**System Information**
 - OS: windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 1.8.9-11.15.1.2318-1.8.9
 - FDPClient Version: 2.01

**Other Installed Mods**
n/a

**Additional info**

**Comment by zWTbz** [comment]
try this https://github.com/UnlegitMC/FDPClient/issues/618#issue-1044980684
