### ISSUE TITLE
Better graphics for the client

### ISSUE THREAD

**Issue by FdpIsBetterThanNovalineInMyOpinion** [UnlegitMC/FDPClient#665]
Like novaline and more text functions like playtime kills and gamewins or just a stats element

**Comment by llama-for3ver** [comment]
*cough* scripts *cough*

**Comment by dudethis** [comment]
"Like novaline" fdp is already skidded no need to steal more code and ideas for graphical stuff this time
It would be nice if unlegitmc and someone else collabed to add better (original) graphics (that hopefully wount cause more crashes lool)
