### ISSUE TITLE
clickgui/command

### ISSUE THREAD

**Issue by RangelMK** [UnlegitMC/FDPClient#67]
add .focus nick \ killaura would focus only on this entity and infinite aura would also be top to focus on a specific opponent;
I saw this on discord fdpclient the Zywl admin sent it as a suggestion and got 30 yes votes for it to be added

add clickgui astolfo because fdpclient no he has never done clickgui projects and it would be nice to have several new clickguis

**Comment by liulihaocai** [comment]
i'll recode the clickgui using html like what LB nextgen do

**Comment by liulihaocai** [comment]
new clickgui added (0d1c548aecfe894c32e597b492fcffe06298b782)
