### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by l1qrs** [UnlegitMC/FDPClient#68]
if i start my game it says crash repot 
The game crashed whilst initializing game Error: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" Exit code: -1

**Comment by ENDER1355** [comment]
remove FDPClient-1.8 from the directory you install FDPClient

**Comment by l1qrs** [comment]
?
what u mean

**Comment by ENDER1355** [comment]
Issue fixed
