### ISSUE TITLE
How to fix it ?

### ISSUE THREAD

**Issue by A216DISCORD** [UnlegitMC/FDPClient#684]
Gradle error:
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Could not resolve project :ui.
     Required by:
         project :
      > No matching variant of project :ui was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability org.unlegitmc.fdp:ui:v1 declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 15 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'runtimeElements' capability org.unlegitmc.fdp:ui:v1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 15 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')

**Comment by horanDEV** [comment]
how to fix it?
