### ISSUE TITLE
FDP Client 2.0.0 and up CRASHES When i select Legacy UI

### ISSUE THREAD

**Issue by CrabsCoding** [UnlegitMC/FDPClient#685]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When i Select Legacy UI OR HTML UI on FDP Client 2.0.0 and later. IT ALWAYS CRASHES.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur>
1. Open FDP Client
2. Select Legacy UI
3. Crash

**Expected behavior**
I expected it to crash, I HAVE BEEN DEALING WITH IT FOR LIKE 2 MONTHS NOW, AND I HAD TO KEEP USING FDP CLIENT 2.0.0 PRE2. I WANT THE LATEST BYPASSES AND THE LATEST TARGETHUD. PLEASE FIX.

**Screenshots/Video**
https://user-images.githubusercontent.com/89733645/146295571-2f93a6cc-1154-4e23-b11d-6b2a2d17ca61.mp4

**Crash Report**
[hs_err_pid4224.log](https://github.com/UnlegitMC/FDPClient/files/7724119/hs_err_pid4224.log)
File was both TOO BIG AND LONG For Pastebin and for THIS Report. so just pls download it instead

**System Information**
 - OS: [Windows 10 LTSC 21H2 (Nexus LiteOS 10 LTSC)]
 - Minecraft Version: [1.8.9]
 - Forge Version: [1.8.9-forge1.8.9-11.15.1.2318-1.8.9]
 - FDPClient Version: [FDPClient-84bb68b6ddd1e4031c089d228d17a3e5dff10dce]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.

1. FDPClient-84bb68b6ddd1e4031c089d228d17a3e5dff10dce.jar
2. OptiFine_1.8.9_HD_U_M6_pre2_MOD.jar
3. ChromaHUD-3.0 (1.8.9).jar

**Additional info**
Please fix. i also forgot about something. Here is my Java Arguments Or JVM Arguments: 

-Xms2G -Xmx2G -Xmn128m -XX:+AggressiveOpts -XX:+UseG1GC -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -noverify

Status Right now: I did bypass the Legacy UI Crashing. but the FONT IS Glitching out. becoming either white. or missing texture.

**Comment by llama-for3ver** [comment]
https://github.com/UnlegitMC/FDPClient/issues/618
try this
btw if you can't see the optition add it in

**Comment by llama-for3ver** [comment]
also optifine + anything liquidbounce = issues so remove it

**Comment by CrabsCoding** [comment]
> #618 try this btw if you can't see the optition add it in

OMFG. Removing Optifine didnt do the trick. BUT DOING THE FONT BUG FIX WORKED. THANK YOU SO MUCH DUDEEEEEEE

**Comment by CrabsCoding** [comment]
> #618 try this btw if you can't see the optition add it in

a slight follow up to what i said about it fixing the crash. it DID Fix the crash. BUT The Font is bugging out. like SOME TEXT ARE EITHER MISSING TEXTURE OR JUST PURE WHITE

**Comment by llama-for3ver** [comment]
> > #618 try this btw if you can't see the optition add it in
> 
> a slight follow up to what i said about it fixing the crash. it DID Fix the crash. BUT The Font is bugging out. like SOME TEXT ARE EITHER MISSING TEXTURE OR JUST PURE WHITE.
> 
> I'm gonna try to reset my JVM Arguments. then see if it did anything.
> 
> Tested it out. did like ABSOLUTELY NOTHING. i think im just gonna downgrade versions to just 2.0.0 BUT OFC NOT 2.0.0 PRE2.
> 
> ALTHOUGH This was when i was using OPTIFINE. If the white text box still appears in 2.0.0. i have no choice but to remove optifine.
> 
> 2.0.0 dont support the font fix. i might as well just resort to removing OPTIFINE.
> 
> Not even Removing Optifine done the trick. i might as well make the font into minecraft font.

exact same with me

**Comment by CrabsCoding** [comment]
> 

Im just gonna try and Ask the dev to Modify the 2.0.2 version BUT With the 2.0.0 PRE2 Font renderer. as now. i know. its not the GUI, its not the buttons. ANYTHING. JUST THE FONTS

**Comment by llama-for3ver** [comment]
also it is meesing up textures, ender chest looks like a COW and my inventory is a fkng EBOY SKIN
also for me optifine just makes the screen pure white on the title screen and spams opengl errors (also affects latest lb ersion)

**Comment by CrabsCoding** [comment]
> also it is meesing up textures, ender chest looks like a COW and my inventory is a fkng EBOY SKIN also for me optifine just makes the screen pure white on the title screen and spams opengl errors (also affects latest lb ersion)

Yeah same. BUT Oh wait. you said enderchest? yeah for SOME Reason. my Chests are PURE WHITE, BUT my inventory is fine. but the SUDDEN turned to white Font error. makes it look like the game is slowly currupting. one by one.
