### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by igordg1** [UnlegitMC/FDPClient#689]
Um problema que eu estou a bom tempo, quando entramos no FDP CLIENT, clico no botão de cima que é onde aparecem diversas opções como ALT Manager e Multiplayer. Mas quando entramos no Client, existem 2 botões, o de cima e o de baixo, quando clico no de baixo o meu jogo crasha. (Acredito eu que seja para configurar o Client pelo site). Talvez seja meu computador, mas meu amigo também teve esse erro.

Versão que eu entro para usar o Clirnt: ForgeOptfine 1.8.9

**Comment by llama-for3ver** [comment]
...
logs?
