### ISSUE TITLE
[Bug] FDP crashes AGAIN first it worked with legacy ui. then it crashed then i tried to restart it and pressed legacy ui. boom crashed again

### ISSUE THREAD

**Issue by JustN0ah** [UnlegitMC/FDPClient#692]
**Describe the bug**
FDP crashes AGAIN first it worked with legacy ui. then it crashed then i tried to restart it and pressed legacy ui. boom crashed again

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by zWTbz** [comment]
where crash report?

**Comment by liulihaocai** [comment]
yea where crash report?

**Comment by Pyroks** [comment]
Delete folder FDP client-1.8. Before deleting, pull out the settings and scripts from there

**Comment by dudethis** [comment]
bruh post the crash report so it doesn't happen again in a future update
