### ISSUE TITLE
Try Ultralight GPU Render

### ISSUE THREAD

**Issue by contionability** [UnlegitMC/FDPClient#698]
@liulihaocai https://github.com/CCBlueX/LiquidBounce/blob/855edba38084846e27b25500e0726a3e37d1bcf9/src/main/kotlin/net/ccbluex/liquidbounce/render/ultralight/UltralightEngine.kt

**Comment by liulihaocai** [comment]
GPU Renderer is required a GLFW window id, but Minecraft older than 1.13 don't use GLFW to create window, it uses the Display API in LWJGL2

**Comment by contionability** [comment]
az 那没事了
/草
