### ISSUE TITLE
[Bug] <fps is shit.>

### ISSUE THREAD

**Issue by negroshooter991** [UnlegitMC/FDPClient#700]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<My laptop is low ended and sucks and whenever i launch fdp client i get like 10 fps ingame and freezes every 5 seconds. but when i launch liquidbounce i have like over 90+ fps>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. get the fdp client mod
2. put it in the minecraft/mods
3. launch the game
4. in game the fps are shit.

**Expected behavior**
<buttery smooth fps just like in liquid bounce>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <optifine 1.8.9 thats it.>

**Additional info**
<Add any other context about the problem here.>

**Comment by negroshooter991** [comment]
Happens every single time.

**Comment by luxuwu** [comment]
laptop moment

**Comment by Arcadius159** [comment]
try to allocate more ram in launcher. 4 Gigs should be enough. This should fix the freezing issue

**Comment by dudethis** [comment]
yes, there is a performance issue. theres no real reason to use fdp. there are other free clients. also im on a 70$ pc and i get 20fps.. so....

**Comment by liulihaocai** [comment]
#618 our vertex font renderer not friendly with cheat graphic cards sorry

**Comment by llama-for3ver** [comment]
@liulihaocai without the vertex font fix thingy the client wont launch, with it non vanilla fonts are broken

**Comment by llama-for3ver** [comment]
is there a way to make fdp ALWAYS use the minecraft font?
