### ISSUE TITLE
How to use scripts

### ISSUE THREAD

**Issue by Siddhantisback** [UnlegitMC/FDPClient#702]
Please help

**Comment by exit-scammed** [comment]
short answer: download, put into fdp folder\scripts, open game, profit

long answer: (for windows)
1. Press Windows + R to open Run window.
2. Type `%appdata%\.minecraft\FDPClient-1.8` and press Enter. A window will be opened.
3. Drag your script file (.js) into that window.
4. Run your Minecraft Launcher and run Minecraft.
5. profit

**Comment by liulihaocai** [comment]
the same as LiquidBounce
