### ISSUE TITLE
Fdp client crashing

### ISSUE THREAD

**Issue by dxxvy** [UnlegitMC/FDPClient#706]
Whenever i use fdp client with forge right when i start it it crashes

**Comment by A216DISCORD** [comment]
Maybe some mod in your mods folder make fdp crash

**Comment by SakurajimaMai02** [comment]
dont use optifine m5

**Comment by llama-for3ver** [comment]
send
logs

**Comment by FartCum** [comment]
> Whenever i use fdp client with forge right when i start it it crashes

https://deletefdp.today 

the solution :axothumbsup:
