### ISSUE TITLE
Rename FDP 2.0.0 to FDP 2.0.2 on website

### ISSUE THREAD

**Issue by Arcadius159** [UnlegitMC/FDPClient#710]
When you are downloading client you download a file named FDPClient-2.0.0, but the version is 2.0.2
Sure its not a big problem but it may confuse new users when they need 2.0.2 and they cant find it...

**Comment by FortCheese** [comment]
> When you are downloading client you download a file named FDPClient-2.0.0, but the version is 2.0.2 Sure its not a big problem but it may confuse new users when they need 2.0.2 and they cant find it...

https://sigmaclient.info
