### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by fpfcom123456** [UnlegitMC/FDPClient#713]
Why i cant join minemora is there any prob with connected to server? rep me
![image](https://user-images.githubusercontent.com/97375655/148670489-8d7b0f0f-a5ef-4d59-b531-8b72d09a9f6b.png)
![image](https://user-images.githubusercontent.com/97375655/148670506-4b64d899-525b-448c-b019-f8c3a6746d42.png)

**Comment by contionability** [comment]
may closed
or try to turn off your vpn and try again
