### ISSUE TITLE
[Bug] <Fps drop, and font no renders>

### ISSUE THREAD

**Issue by iJese-New** [UnlegitMC/FDPClient#715]
![image](https://user-images.githubusercontent.com/77810458/149388792-d03c1037-3e42-455e-a395-26f654ccb11b.png)
help please

**Comment by F3D7P6hxg** [comment]
how many memory you allocated,also you can install optifine with fdp client,also,if you have font issue,
    Go to 'fdp folder'
    open 'Special.json'
    set the "use-glyph-fontrenderer" 'to true'
    launch the game and it will be fixed

**Comment by iJese-New** [comment]
muchas gracias gringo

**Comment by liulihaocai** [comment]
i make font renderer use VBO, that cost less memory 2e7bfcff0731ca1aaee28fd474c43ca347400cc3
