### ISSUE TITLE
[Bug] <The Text is weird>

### ISSUE THREAD

**Issue by IAintA7** [UnlegitMC/FDPClient#726]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<When i installed this client the fonts are almost shuffling that i dont understand.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Fonts are weird
2. Deleted some mods still didn't fixed
3. 
4. 

**Expected behavior**
<I don't know when i deleted some mods it's still same issue>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
![2022-01-17_19 09 49](https://user-images.githubusercontent.com/97886211/149760682-12c38c0b-d366-4041-a0e8-657a0023f71e.png)
**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>
The mods are
Better FPS 1.2.0
ChromaHUD 3.0
foamfix 0.6.3 1.8x
Patcher 1.7.0
PerspectiveReduxMod 0.0.4
Player API 1.0
TexFix 4.0
TimeChanger 1.0
**Additional info**
<Add any other context about the problem here.>

**Comment by SakurajimaMai02** [comment]
thats bcz ur graphic card is too bad and Out of Memory（OpenGL error 1285). Try to use Discrete graphics card.

**Comment by k6d** [comment]
I believe you can fix this by following [issue 618](
https://github.com/UnlegitMC/FDPClient/issues/618)

**Comment by liulihaocai** [comment]
i make font renderer use VBO, that cost less memory b1a5f57b9d6bd08b4d5ed34a0a04d2bd0f7309e6
