### ISSUE TITLE
[Bug] Game crashes whilst loading (forgot to fill out OS information)

### ISSUE THREAD

**Issue by Maks7594** [UnlegitMC/FDPClient#727]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The game runs, and loads all the things, but then it printed out "[FileManager] Loaded config: xray-blocks.json." and became unresponsive.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Just load Minecraft

**Expected behavior**
Game should load into the GUI selection menu

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
i can't

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by Maks7594** [comment]
How do i delete a issue

**Comment by Maks7594** [comment]
oh, and no other mods than fdp

**Comment by WannaCry1LoL** [comment]
Step 1: start & wait till it gets stuck
Step 2: end discord with Taskmanager
Step 3: fdp should now crash
Step 4: start again (don't open discord yet)
Step 5: if it reaches the main menu you can start discord again

**Comment by Maks7594** [comment]
> Step 1: start & wait till it gets stuck Step 2: end discord with Taskmanager Step 3: fdp should now crash Step 4: start again (don't open discord yet) Step 5: if it reaches the main menu you can start discord again For anyone asking it seems to be a first time problem with fdps discord rpc while using betterdiscord/toggle game activity plugin

can i just open fdp without discord?

**Comment by k6d** [comment]
> > Step 1: start & wait till it gets stuck Step 2: end discord with Taskmanager Step 3: fdp should now crash Step 4: start again (don't open discord yet) Step 5: if it reaches the main menu you can start discord again For anyone asking it seems to be a first time problem with fdps discord rpc while using betterdiscord/toggle game activity plugin
> 
> can i just open fdp without discord?

just try it and see if it works???

**Comment by liulihaocai** [comment]
> > Step 1: start & wait till it gets stuck Step 2: end discord with Taskmanager Step 3: fdp should now crash Step 4: start again (don't open discord yet) Step 5: if it reaches the main menu you can start discord again For anyone asking it seems to be a first time problem with fdps discord rpc while using betterdiscord/toggle game activity plugin
> 
> can i just open fdp without discord?

i gonna make discord rpc load async
