### ISSUE TITLE
[Bug] <Title Here>

### ISSUE THREAD

**Issue by iiMqtt** [UnlegitMC/FDPClient#728]
**Describe the bug**
Load FDP, game window goes black and becomes unresponsive, crashes after a while with EXCEPTION_ACCESS_VIOLATION

**To Reproduce**
1 - Set FDP Args to: -Dfdp-legacy-ui -Dno-server-block -Djavax.net.ssl.trustStoreType=Windows-ROOT -noverify -Xmx4G - 
     XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 - 
     XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M  (without these it crashes even faster)
2 - Have "use-glyph-fontrenderer": true in special.json
3 - Load FDP
4 - Game window becomes black and unresponsive after Sound engine starts, crashes

**Expected behavior**
FDP Loaded, can skid your collision fly.

**Crash Report*

```text
13:13:13.175
Created: 16x16 textures-atlas
13:13:16.572

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb9b302bfa, pid=1472, tid=0x0000000000001f3c
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22bfa]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Laptop\Desktop\Minecraft\!!!!!Versions\FDP\hs_err_pid1472.log
#
# If you would like to submit a bug report, please visit:
#   https://bell-sw.com/support
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
13:13:16.586
Process crashed with exit code 1
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDP Client Version: 2.0.0

**Other Installed Mods**
N/A

**Additional info**
There are tons of other crashes with FDP too, using no JVM Args or Default Args crashes with EXEPTION_ACCESS_VIOLATION, please fix this lmao

**Comment by F3D7P6hxg** [comment]
https://ugetfix.com/ask/how-to-fix-exception-access-violation-error-on-windows-10/
