### ISSUE TITLE
[Bug] <Title Here>crash in game

### ISSUE THREAD

**Issue by NotDevilhunter** [UnlegitMC/FDPClient#732]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>
I download fdp 2.0.2 and btw why tf every fdp version. Is named as fdp 2.0.0? And i opened it it was all good but then i load a config and go to the menu turn on kill aura and ir crash :(
**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.
Yeah my game crashes when i try to use some features like killaura

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]
-android (pojav launcher lmfao) liquidbounce works 200 fps in my phone tho
1.8.9
Latest
2.0.2
**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>
- nothing

**Additional info**
<Add any other context about the problem here.>

**Comment by llama-for3ver** [comment]
add f*cking logs how many times do i have to tell people

**Comment by contionability** [comment]
log plz
and why thw version you download is 2.0.2 instead of 2.1.0(2.1.1) ?
