### ISSUE TITLE
<suggestion>spartan fly

### ISSUE THREAD

**Issue by F3D7P6hxg** [UnlegitMC/FDPClient#744]
i have found that highjump with stablemotion 0.42 insane bypass spartan,maybe we can make a new fly with this

**Comment by FengXiaoSkidGod** [comment]
fly Clip mode
clip-x 8.0
clip-y 5.0
clip-z 8.0 
Can bypass Spartan with low VL

**Comment by FengXiaoSkidGod** [comment]
and matrix1.17 mode maybe can bypass to

**Comment by F3D7P6hxg** [comment]
with jump potion you can jump more higher,like about 20blocks,and also i found that verus3 fly can bypass spartan but not too long,spartan is broken lol

**Comment by llama-for3ver** [comment]
maybe skid sigmas spartan fly? the one thats like verus3?
