### ISSUE TITLE
Not able to use FDP

### ISSUE THREAD

**Issue by ProMinecrafter13** [UnlegitMC/FDPClient#759]

**Comment by WannaCry1LoL** [comment]
Pov: no logs, no os Infos, other mods not specfied, circumstances not specified, crash/other not specified

This is how to ***NOT*** write a bugreport

**Comment by PeralolXD** [comment]
@WannaCry1LoL Insane bug report ikr

**Comment by ProMinecrafter13** [comment]
I figured out the problem and also i had opened this by mistake 😅😅😅😅

**Comment by ProMinecrafter13** [comment]
The problem was that my computer didnt had the required video card to run it
