### ISSUE TITLE
FDP CLIENT IS CLOSED

### ISSUE THREAD

**Issue by Benjaa0088** [UnlegitMC/FDPClient#761]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>
--When opening fdp client in an offline world of minecraft the game works perfectly for me but when I try to enter a server the client closes by itself.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>
--what should have happened is that it did not close by itself and could play on the server

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.
--the game closes completely, it is not a crash since I do not get any errors in the launcher

```text
[Paste Here]
```

**System Information**
 - OS: Windows 7 32 Bits
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: The latest 2.1.2

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- OptiFine_1.8.9_HD_U_M5 and FDP Client

**Additional info**
<Add any other context about the problem here.>

**Comment by SakurajimaMai02** [comment]
lowiq｜dont use OF-M5

**Comment by suckma420** [comment]
smh windows 32 bit

**Comment by Benjaa0088** [comment]
> lowiq｜dont use OF-M5

What OptiFine do you recommend?

**Comment by contionability** [comment]
OF-L5 or older
M5 will random crash even on legit gameplay :(
