### ISSUE TITLE
If someone has time please fix fdp for pojav launcher

### ISSUE THREAD

**Issue by NotDevilhunter** [UnlegitMC/FDPClient#762]
Yes i dont have pc i play on phone(8gb ram btw hehehe) on pojav launcher the only version which works on pojav launcher is v2.0.0 pre2 after this version all version had bugs like opening combat tab will crash the game and toggling killaura will crash the game y'all if got time download pojav and test ur client out pls there is a community for it too...

**Comment by Astroynm** [comment]
LOL, i also sometimes use pojav but everything works
