### ISSUE TITLE
Error Not A JSON Object

### ISSUE THREAD

**Issue by zWTbz** [UnlegitMC/FDPClient#85]
My game cant start

Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"

Full Log from intellij console:
https://pastebin.com/Q77KuhiM

**Comment by zWTbz** [comment]
[error.txt](https://github.com/UnlegitMC/FDPClient/files/7018140/error.txt)

**Comment by liulihaocai** [comment]
oops, your config was broken and idk why

**Comment by zWTbz** [comment]
> oops, your config was broken and idk why

i delete my config and keep error

**Comment by ll11l1lIllIl1lll** [comment]
del mcDataDir/FDPClient/*
